import fs from 'node:fs';
import { execFileSync } from 'node:child_process';

const BASE='6e3fd61d046ff67b33952526f2aadb7219e31111';
const files={
  'src/examenes_modes.jsx':'9d86826c3c3d0ac12e4a915d461e9fcc42be3705',
  'src/examenes_bundle.jsx':'4ee147afe2c06c3318d075b478a47497994a93dc',
};
const hash=s=>execFileSync('git',['hash-object','--stdin'],{input:s,encoding:'utf8'}).trim();
const count=(s,x)=>s.split(x).length-1;
const helper=`function examAdminSafeUserError(response, fallback, context) {\n  const raw = response && (response.mensaje || response.error || (response.errores && response.errores.join(' · ')));\n  const detail = String(raw == null ? '' : raw).trim();\n  if (detail) console.warn(\`[CS21A210BC][AdminMode][\${context || 'unknown'}]\`, detail);\n  return fallback;\n}\n\n`;
const anchor='function ActivationBackendPanel({ onPreview }) {';
const activationOld="const detail = r && (r.mensaje || r.error || (r.errores && r.errores.join(' · ')));\n      setErr(detail || 'No se pudo completar la operación.');";
const activationNew="setErr(examAdminSafeUserError(r, 'No se pudo completar la operación.', 'activation'));";
const opsOld="else { setMsg(''); setErr((r && (r.mensaje || r.error)) || 'No se pudo completar la operación.'); }";
const opsNew="else { setMsg(''); setErr(examAdminSafeUserError(r, 'No se pudo completar la operación.', 'backend_operations')); }";

function transform(s,path){
  if (count(s,anchor)!==1) throw new Error(`${path}: Activation anchor count mismatch`);
  if (count(s,activationOld)!==1) throw new Error(`${path}: activation preimage count mismatch`);
  if (count(s,opsOld)!==1) throw new Error(`${path}: operations preimage count mismatch`);
  if (s.includes('function examAdminSafeUserError(')) throw new Error(`${path}: helper already present`);
  s=s.replace(anchor,helper+anchor);
  s=s.replace(activationOld,activationNew);
  s=s.replace(opsOld,opsNew);
  return s;
}

for(const [path,expected] of Object.entries(files)){
  const current=fs.readFileSync(path,'utf8');
  if(hash(current)!==expected) throw new Error(`${path}: expected frozen BB preimage ${expected}, got ${hash(current)}`);
  const base=execFileSync('git',['show',`${BASE}:${path}`],{encoding:'utf8',maxBuffer:20*1024*1024});
  if(base!==current) throw new Error(`${path}: working copy differs from exact BB base`);
  const next=transform(current,path);
  fs.writeFileSync(path,next);
}

const bbPath='scripts/qa_examenes_admin_effective_boundary_cs21a210bb.mjs';
const bb=`import fs from 'node:fs';\nimport { execFileSync } from 'node:child_process';\n\nconst expected = {\n  'src/examenes_modes.jsx': '9d86826c3c3d0ac12e4a915d461e9fcc42be3705',\n  'src/examenes_bundle.jsx': '4ee147afe2c06c3318d075b478a47497994a93dc',\n};\nconst exact=process.argv.includes('--exact-import');\nconst blob = text => execFileSync('git',['hash-object','--stdin'],{input:text,encoding:'utf8'}).trim();\nfor (const [path, sha] of Object.entries(expected)) {\n  const s = fs.readFileSync(path,'utf8');\n  for (const fn of ['function AdminMode(','function ActivationBackendPanel(','function BackendOperationsPanel(','function TeacherBackendReviewPanel(']) {\n    if (!s.includes(fn)) throw new Error(\`${path}: missing \${fn}\`);\n  }\n  if (!s.includes('<ActivationBackendPanel onPreview={onPreview} />')) throw new Error(\`${path}: ActivationBackendPanel not mounted in AdminMode\`);\n  if (!s.includes('<BackendOperationsPanel />')) throw new Error(\`${path}: BackendOperationsPanel not mounted in AdminMode\`);\n  if (s.includes('<TeacherBackendReviewPanel')) throw new Error(\`${path}: TeacherBackendReviewPanel unexpectedly mounted\`);\n  const activationRaw = \"const detail = r && (r.mensaje || r.error || (r.errores && r.errores.join(' · ')));\";\n  const opsRaw = \"else { setMsg(''); setErr((r && (r.mensaje || r.error)) || 'No se pudo completar la operación.'); }\";\n  if (exact) {\n    if (blob(s) !== sha) throw new Error(\`${path}: frozen BA preimage mismatch\`);\n    if ((s.split(activationRaw).length - 1) !== 1) throw new Error(\`${path}: activation raw projection count mismatch\`);\n    if ((s.split(opsRaw).length - 1) !== 1) throw new Error(\`${path}: operations raw projection count mismatch\`);\n  } else {\n    if ((s.split(activationRaw).length - 1) !== 0) throw new Error(\`${path}: activation raw projection reintroduced\`);\n    if ((s.split(opsRaw).length - 1) !== 0) throw new Error(\`${path}: operations raw projection reintroduced\`);\n    if (!s.includes('function examAdminSafeUserError(')) throw new Error(\`${path}: safe admin helper missing\`);\n    if (!s.includes(\"setErr(examAdminSafeUserError(r, 'No se pudo completar la operación.', 'activation'));\")) throw new Error(\`${path}: safe activation projection missing\`);\n    if (!s.includes(\"setErr(examAdminSafeUserError(r, 'No se pudo completar la operación.', 'backend_operations'))\")) throw new Error(\`${path}: safe operations projection missing\`);\n  }\n  const adminStart=s.indexOf('function AdminMode(');\n  const adminSlice=s.slice(adminStart);\n  if (!adminSlice.includes('<ActivationBackendPanel onPreview={onPreview} />') || !adminSlice.includes('<BackendOperationsPanel />')) throw new Error(\`${path}: effective admin mount relation missing\`);\n}\nconsole.log(exact ? 'CS21A210BB exact audit snapshot PASS' : 'CS21A210BB descendant-safe admin boundary PASS');\nconsole.log('TEACHER_BACKEND_REVIEW_PANEL_MOUNTED=NO');\n`;
fs.writeFileSync(bbPath,bb);

const guard=`import fs from 'node:fs';\nimport { execFileSync } from 'node:child_process';\nconst BASE='${BASE}';\nconst expected={\n  'src/examenes_modes.jsx':'9d86826c3c3d0ac12e4a915d461e9fcc42be3705',\n  'src/examenes_bundle.jsx':'4ee147afe2c06c3318d075b478a47497994a93dc',\n};\nconst hash=s=>execFileSync('git',['hash-object','--stdin'],{input:s,encoding:'utf8'}).trim();\nconst count=(s,x)=>s.split(x).length-1;\nconst helper=${JSON.stringify(helper)};\nconst anchor=${JSON.stringify(anchor)};\nconst activationOld=${JSON.stringify(activationOld)};\nconst activationNew=${JSON.stringify(activationNew)};\nconst opsOld=${JSON.stringify(opsOld)};\nconst opsNew=${JSON.stringify(opsNew)};\nfunction transform(s,path){\n  if(count(s,anchor)!==1||count(s,activationOld)!==1||count(s,opsOld)!==1) throw new Error(\`${path}: BC preimage cardinality mismatch\`);\n  s=s.replace(anchor,helper+anchor).replace(activationOld,activationNew).replace(opsOld,opsNew);\n  return s;\n}\nfor(const [path,sha] of Object.entries(expected)){\n  const base=execFileSync('git',['show',\`${BASE}:\${path}\`],{encoding:'utf8',maxBuffer:20*1024*1024});\n  if(hash(base)!==sha) throw new Error(\`${path}: exact BB preimage hash mismatch\`);\n  const current=fs.readFileSync(path,'utf8');\n  const reconstructed=transform(base,path);\n  if(current!==reconstructed) throw new Error(\`${path}: current source is not exact BC reconstruction\`);\n  if(count(current,'function examAdminSafeUserError(')!==1) throw new Error(\`${path}: helper cardinality mismatch\`);\n  if(current.includes(activationOld)||current.includes(opsOld)) throw new Error(\`${path}: raw admin projection remains\`);\n  if(!current.includes('<ActivationBackendPanel onPreview={onPreview} />')||!current.includes('<BackendOperationsPanel />')) throw new Error(\`${path}: admin mounts changed\`);\n  if(current.includes('<TeacherBackendReviewPanel')) throw new Error(\`${path}: unmounted teacher legacy panel unexpectedly mounted\`);\n}\nconsole.log('CS21A210BC exact reconstruction PASS');\nconsole.log('FUNCTIONAL_SCOPE=ActivationBackendPanel+BackendOperationsPanel');\nconsole.log('E2=NO');\n`;
fs.writeFileSync('scripts/qa_examenes_admin_safe_errors_cs21a210bc.mjs',guard);

const workflow=`name: QA Examenes Admin Safe Errors CS21A210BC\non:\n  push:\n    branches: [fix/examenes-admin-safe-errors-cs21a210bc]\n  pull_request:\n    paths:\n      - 'src/examenes_modes.jsx'\n      - 'src/examenes_bundle.jsx'\n      - 'scripts/qa_examenes_admin_safe_errors_cs21a210bc.mjs'\n      - 'scripts/qa_examenes_admin_effective_boundary_cs21a210bb.mjs'\n      - '.github/workflows/qa-examenes-admin-safe-errors-cs21a210bc.yml'\npermissions:\n  contents: read\njobs:\n  source-guard:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n        with: {fetch-depth: 0}\n      - run: npm install --no-save @babel/parser@7.28.4\n      - name: Parse JSX\n        run: node -e \"const fs=require('fs'),p=require('@babel/parser');for(const f of ['src/examenes_modes.jsx','src/examenes_bundle.jsx'])p.parse(fs.readFileSync(f,'utf8'),{sourceType:'script',plugins:['jsx']});\"\n      - name: Verify BC exact reconstruction\n        run: node scripts/qa_examenes_admin_safe_errors_cs21a210bc.mjs\n      - name: Regress BB effective admin ownership\n        run: node scripts/qa_examenes_admin_effective_boundary_cs21a210bb.mjs\n      - name: Regress BA teacher boundary\n        run: node scripts/qa_examenes_teacher_safe_errors_cs21a210ba.mjs\n      - name: Regress AY StudentMode\n        run: node scripts/qa_examenes_student_safe_errors_cs21a210ay.mjs\n      - name: Verify V3 non-regression\n        run: |\n          set -o pipefail\n          node scripts/audit_raw_user_error_surface_v3_cs21a210s.mjs | tee /tmp/v3-bc.txt\n          findings=$(grep -oE 'DIRECT_RAW_SINK_FINDINGS=[0-9]+' /tmp/v3-bc.txt | cut -d= -f2)\n          files=$(grep -oE 'FILES_WITH_FINDINGS=[0-9]+' /tmp/v3-bc.txt | cut -d= -f2)\n          test \"$findings\" -le 30\n          test \"$files\" -le 12\n      - name: Diff hygiene\n        run: git diff --check ${BASE}\n`;
fs.writeFileSync('.github/workflows/qa-examenes-admin-safe-errors-cs21a210bc.yml',workflow);

const doc=`# CS21A210BC · Exámenes · errores seguros en frontera admin efectiva\n\nBase exacta: PR #254 / \`${BASE}\`.\n\n## Alcance\n\nCorrige únicamente la presentación de error de las dos superficies admin demostradas como efectivas por CS21A210BB, manteniendo sincronizados \`src/examenes_modes.jsx\` y \`src/examenes_bundle.jsx\`:\n\n1. \`ActivationBackendPanel\`;\n2. \`BackendOperationsPanel\`.\n\nEl helper \`examAdminSafeUserError\` conserva el detalle crudo solo en consola y entrega copy estable a UI. \`TeacherBackendReviewPanel\` continúa sin montarse y no se modifica para reducir métricas.\n\n## Contrato congelado\n\nNo modifica endpoints, payloads, permisos, ejecución de operaciones administrativas, StudentMode, revisión docente, backend, Apps Script, Drive ACL, main ni PROD. El guard reconstruye ambos archivos desde las preimágenes BB exactas y exige igualdad byte por byte con el candidato.\n\nE0: sí. E1: sujeto a Actions. E2: NO. \`BACKEND CURRENT SNAPSHOT UNVERIFIED\` vigente.\n`;
fs.writeFileSync('00_DOCUMENTACION/EXAMENES_ADMIN_SAFE_ERRORS_CS21A210BC_2026-09-01.md',doc);

console.log('CS21A210BC bootstrap patch generated');
