import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const Babel=require('../vendor/babel.js');
const source=fs.readFileSync(new URL('../src/student_modules.jsx',import.meta.url),'utf8');
const start=source.indexOf('const EVAL_SCHEMA_SM = [');
const stop=source.indexOf('// F108',start);
assert(start>=0 && stop>start,'Rubric functions available');
const context={};
vm.runInNewContext(source.slice(start,stop)+'\nthis.build=_smCanonicalRows_;this.schema=_smSchemaForLevelF109_;this.program=_smProgramForLevelF109_;this.hasPoints=_smHasOfficialPointsF109_;',context);
const grades=[{nivel:'B1',tipo_oficial:'ESCRITO_1',programa:'SIN_INA',nota:4,max:15,registrada:true,estado:'REGISTRADA'}];
const ina=context.build(grades,[],'B1','INA');
assert.equal(ina.length,8,'INA needs 8 components');
assert.equal(ina.reduce((x,r)=>x+r.max,0),100,'INA total 100');
assert.equal(ina.find(x=>x.key==='ESCRITO_1').max,5,'Written lesson 18 = 5');
assert.equal(ina.find(x=>x.key==='ESCRITO_1').pct,80,'Written 4/5 = 80%');
assert.equal(ina.find(x=>x.key==='ESCRITO_2').max,5,'Written lesson 32 = 5');
assert.equal(ina.filter(x=>x.key.startsWith('ORAL')).length,4,'4 orals');
assert.equal(ina.find(x=>x.key==='SOCIAL').max,10,'Social = 10');
assert.equal(ina.find(x=>x.key==='ICAN').max,20,'ICAN = 20');
assert.equal(ina.find(x=>x.key==='ICAN').registrada,false,'Missing ICAN report must NOT award points');
assert.equal(ina.find(x=>x.key==='ICAN').estado,'SIN_NOTA','Missing ICAN shown as ungraded');
assert.equal(context.program(grades,'B1','INA'),'INA','Authoritative group overrides wrong SIN_INA from backend');
const free=context.build(grades,[],'B1','SIN_INA');
assert.equal(free.length,7,'Non INA must not invent I CAN');
assert.equal(free.reduce((x,r)=>x+r.max,0),100,'Non-INA existing rubric 100');
assert.equal(free.find(x=>x.key==='ESCRITO_1').max,15,'Non-INA written unchanged');
const rawIcan={nivel:'B1',tipo_oficial:'ICAN',programa:'INA',nota:2.5,max:20,pct_asistencia:75,registrada:true,registradas:3,requeridas:16,estado:'EN_CURSO'};
const partial=context.build([...grades,rawIcan],[],'B1','INA').find(x=>x.key==='ICAN');
assert.equal(partial.nota,2.5);
assert.equal(partial.pct,12.5,'I CAN percentage is points earned out of its 20-point weight, not attendance among held sessions');
assert.equal(partial.faltante,true,'3 of 16 not completed');
assert.equal(context.hasPoints([partial],false),true,'I CAN partial score must remain visible');
assert.equal(context.hasPoints([],false),false,'Empty grades must not pretend to be zero');
assert.equal(context.hasPoints([{registrada:false,estado:'VENCIDA_0'}],false),true,'Official expired zero must remain visible');
assert.equal(context.hasPoints([],true),true,'Closed level must retain official summary');
assert(source.includes("row.key==='ICAN'&&row.faltante?null:gradeLetter(pct)"),'Ongoing I CAN must not receive a failing letter grade');
const finished=context.build([...grades,{...rawIcan,registradas:16,nota:20}],[],'B1','INA').find(x=>x.key==='ICAN');
assert.equal(finished.faltante,false,'16 of 16 completed');
const app=fs.readFileSync(new URL('../src/app.jsx',import.meta.url),'utf8');
const html=fs.readFileSync(new URL('../campus.html',import.meta.url),'utf8');
assert(app.includes('student_modules.jsx?v=F109AINAGRADES20261010'));
assert(html.includes('src/app.jsx?v=F109AINAGRADES20261010'));
new vm.Script(Babel.transform(source,{presets:['react'],plugins:['transform-block-scoping']}).code);
console.log('QA_F109A_INA_15_15_5_15_15_5_10_20_PASS');
console.log('QA_F109A_NO_FAKE_ICAN_AND_SIN_INA_REGRESSION_PASS');
console.log('QA_F109A_FRONTEND_JSX_PASS');
