// F98.4-Z6-CS21A101 · Historial académico: seguimiento exclusivo del desembolso 01
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const {LEVEL,LEVEL_ORDER,TONE,clean,levelId,levelText}=N;
function MovementBadge({row}){const applied=!!row.appliedInSystem,tone=row.moraState==='SI'?['Mora SI','#FDECEC','#A12828','#E8B1B1']:row.moraState==='NO'?['Mora NO','#EAF6ED','#246B35','#B8D9C0']:null,label=clean(row?.movementBadgeLabel)||(applied?'Académico 01 aplicado':'Académico 01 pendiente');return <div className="master-conape-movement-stack"><span className="master-conape-movement-badge" data-applied={applied?'true':'false'} title="Solo el desembolso académico 01 requiere seguimiento de la Academia">{applied?'✓ ':''}{label}</span>{tone&&<span className="master-conape-mora-badge" style={{background:tone[1],color:tone[2],borderColor:tone[3]}}>{tone[0]}</span>}</div>}
function AcademicHistory({items,row}){const rows=(Array.isArray(items)?items:[]).slice().sort((a,b)=>(LEVEL_ORDER[clean(a?.level).toUpperCase()]||99)-(LEVEL_ORDER[clean(b?.level).toUpperCase()]||99)),target=levelId(row),hasExact=rows.some(x=>clean(x?.level).toUpperCase()===target);if(!rows.length)return <div className="master-conape-history-grid"><div className="master-conape-history-item" data-has-alert="true"><span className="master-conape-history-level">{levelText(row).toUpperCase()}</span><span className="master-conape-history-period">—</span><span className="master-conape-history-status">SIN REGISTRO</span><div className="master-conape-history-alert"><MovementBadge row={row}/></div></div></div>;return <div className="master-conape-history-grid">{rows.map((h,i)=>{const status=clean(h.status||'SIN_REGISTRO').toUpperCase(),tone=TONE[status]||['#F2F0EC','#69635B','#D8D1C7'],hasNote=clean(h.note)!=='',exact=clean(h?.level).toUpperCase()===target;return <div key={`${h.sourceRow||i}-${h.matter||''}`} className="master-conape-history-item" data-has-alert={exact?'true':'false'}><span className="master-conape-history-level">{clean(h.levelLabel||LEVEL[clean(h.level).toUpperCase()]||h.matter||'Nivel').toUpperCase()}</span><span className="master-conape-history-period">{h.periodCode||`${h.year||''}${h.period||''}${h.periodType||''}`}</span><span className="master-conape-history-status" style={{background:tone[0],color:tone[1],borderColor:tone[2]}}>{status}{hasNote?` ${h.note}`:''}</span>{exact&&<div className="master-conape-history-alert"><MovementBadge row={row}/></div>}</div>})}{!hasExact&&<div className="master-conape-history-item" data-has-alert="true"><span className="master-conape-history-level">{levelText(row).toUpperCase()}</span><span className="master-conape-history-period">—</span><span className="master-conape-history-status">NIVEL ENLAZADO</span><div className="master-conape-history-alert"><MovementBadge row={row}/></div></div>}</div>}
Object.assign(N,{MovementBadge,AcademicHistory});
})();
