// F98.4-Z6-CS21A103 · Estado del Panel Maestro con morosidad oficial en vivo
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const{clean,levelId,isAcademicDisbursement01,post,uniqueSorted,dedupeMovementRows,filterRows,compareRows}=N;
function groupFallbackLabel(row){
 const code=clean(row?.group||row?.code),parts=code.split('-'),slot=parts[1]||'',dayCode=slot.replace(/\d/g,''),timeCode=slot.replace(/\D/g,''),days={LM:'LUNES Y MIÉRCOLES',KJ:'MARTES Y JUEVES',LJ:'LUNES A JUEVES',SA:'SÁBADO'}[dayCode]||clean(row?.groupDays)||dayCode||'DÍAS SIN DEFINIR',schedule=clean(row?.groupSchedule)||({69:'6-9 PM',94:'9 AM-4 PM'}[timeCode]||timeCode),teacher=clean(row?.groupTeacher)||'DOCENTE SIN ASIGNAR',consecutive=clean(row?.groupConsecutive)||parts[parts.length-1]||code;
 return[teacher,`${days}${schedule?` ${schedule}`:''}`,consecutive].filter(Boolean).join(' - ');
}
function moraPeriod(month){const n=Number(month)||0;return n>=1&&n<=12?Math.ceil(n/4):0}
function applyMoraLive(row,live){
 if(!live)return row;
 const state=clean(live.state||'SIN_FILA').toUpperCase(),applied=state==='NO';
 return{...row,moraState:state,mora:state==='SI',moraPeriod:Number(live.period)||moraPeriod(row.month),moraYear:Number(live.year)||Number(row.year)||0,moraRowCount:Number(live.count)||0,moraSourceRows:Array.isArray(live.rows)?live.rows:[],moraSourceId:live.sourceId||row.moraSourceId,moraSourceSheet:live.sourceSheet||row.moraSourceSheet,moraVerifiedLive:true,appliedInSystem:applied,applicationState:applied?'APLICADO_EN_SISTEMA':(state==='SI'?'PENDIENTE_MOROSIDAD_SI':'PENDIENTE_SIN_FILA_MOROSIDAD'),followupClosed:applied,followupState:applied?'DESEMBOLSO_01_CERRADO':'DESEMBOLSO_01_PENDIENTE',reviewStep:applied?0:row.reviewStep,reviewClosedReset:applied,applicationBasis:`LIVE_7_MOROSIDAD_${state}`};
}
function useConapePanelData(data,onRefresh){
 const movements=data?.conape?.movements||{},baseRows=React.useMemo(()=>dedupeMovementRows((Array.isArray(movements.rows)?movements.rows:[]).filter(isAcademicDisbursement01)),[data]),financeRows=Array.isArray(data?.collections?.rows)?data.collections.rows:[];
 const[moraLive,setMoraLive]=React.useState({}),[busy,setBusy]=React.useState(false),[msg,setMsg]=React.useState(''),[details,setDetails]=React.useState({}),[editor,setEditor]=React.useState(null),[query,setQuery]=React.useState(''),[groupFilter,setGroupFilter]=React.useState('ALL'),[levelFilter,setLevelFilter]=React.useState('ALL'),[statusFilter,setStatusFilter]=React.useState('ALL'),[periodFilter,setPeriodFilter]=React.useState('ALL'),[whatsappFilter,setWhatsappFilter]=React.useState('ALL'),[sort,setSort]=React.useState({key:'detected',dir:'desc'});
 const all=React.useMemo(()=>baseRows.map(row=>applyMoraLive(row,moraLive[row.id])),[baseRows,moraLive]);
 const liveRef=React.useRef(false),rowsRef=React.useRef(baseRows);rowsRef.current=baseRows;
 const refreshMora=React.useCallback(async(silent=true)=>{if(liveRef.current||!rowsRef.current.length)return;liveRef.current=true;try{const items=rowsRef.current.map(row=>({id:row.id,cedula:row.cedula,year:row.year,month:row.month,period:moraPeriod(row.month)})),result=await post('getConapeMoraStates',{items}),next={};(result.items||[]).forEach(item=>{if(item?.id)next[item.id]=item});setMoraLive(next);if(!silent)setMsg('Morosidad verificada directamente en 7-morosidad oficial.')}catch(error){if(!silent)setMsg(error?.message||String(error))}finally{liveRef.current=false}},[]);
 React.useEffect(()=>{let active=true;const run=()=>{if(active&&document.visibilityState!=='hidden')refreshMora(true)};run();const timer=setInterval(run,20000),focus=()=>refreshMora(true);window.addEventListener('focus',focus);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',focus)}},[refreshMora,baseRows]);
 const financeMap=React.useMemo(()=>{const out={},by={};financeRows.forEach(x=>{const c=clean(x?.code),l=clean(x?.level).toUpperCase();if(!c)return;if(l)out[`${c}|${l}`]=x;(by[c]||(by[c]=[])).push(x)});Object.keys(by).forEach(c=>{if(by[c].length===1)out[c]=by[c][0]});return out},[data]);
 React.useEffect(()=>{const next={};all.forEach(row=>{const c=clean(row?.code);if(c)next[c]=clean(row?.detail)});setDetails(next)},[all]);
 const groupOptions=React.useMemo(()=>{const map=new Map();(Array.isArray(movements.groupOptions)?movements.groupOptions:[]).forEach(item=>{const code=clean(item?.code);if(code)map.set(code,{code,label:clean(item?.label)||groupFallbackLabel({...item,group:code})})});all.forEach(row=>{const code=clean(row?.group);if(code&&!map.has(code))map.set(code,{code,label:clean(row?.groupLabel)||groupFallbackLabel(row)})});return Array.from(map.values()).sort((a,b)=>String(a.label||a.code).localeCompare(String(b.label||b.code),'es',{numeric:true,sensitivity:'base'}))},[data,all]);
 React.useEffect(()=>{if(groupFilter!=='ALL'&&!groupOptions.some(x=>x.code===groupFilter))setGroupFilter('ALL')},[groupOptions,groupFilter]);
 const statusOptions=React.useMemo(()=>uniqueSorted(all.map(r=>clean(r?.academicStatus||'SIN_ESTADO').toUpperCase())),[all]),periodOptions=React.useMemo(()=>uniqueSorted(all.map(r=>`${String(r?.month||0).padStart(2,'0')}/${r?.year||0}`)),[all]);
 const filters={query,level:levelFilter,status:statusFilter,period:periodFilter,whatsapp:whatsappFilter},visible=React.useMemo(()=>filterRows(all,filters).filter(row=>groupFilter==='ALL'||clean(row?.group)===groupFilter).slice().sort((a,b)=>compareRows(a,b,sort)),[all,query,groupFilter,levelFilter,statusFilter,periodFilter,whatsappFilter,sort.key,sort.dir]),pending=visible.filter(r=>!r.appliedInSystem),applied=visible.filter(r=>r.appliedInSystem),originalPending=all.filter(r=>!r.appliedInSystem),originalApplied=all.filter(r=>r.appliedInSystem),hasFilters=!!query||groupFilter!=='ALL'||levelFilter!=='ALL'||statusFilter!=='ALL'||periodFilter!=='ALL'||whatsappFilter!=='ALL',stats={mora:all.filter(r=>r.moraState==='SI').length,levelLinked:all.filter(r=>!!r.level).length,unlinked:all.filter(r=>!r.linked).length};
 function onSort(key){setSort(current=>current.key===key?{key,dir:current.dir==='asc'?'desc':'asc'}:{key,dir:'asc'})}function clearFilters(){setQuery('');setGroupFilter('ALL');setLevelFilter('ALL');setStatusFilter('ALL');setPeriodFilter('ALL');setWhatsappFilter('ALL')}
 async function refresh(){setBusy(true);setMsg('');try{const result=await window.masterAction('actualizarPanelConapeAhora');await onRefresh?.();await refreshMora(false);setMsg(result.mensaje||'CONAPE y morosidad oficial actualizados.')}catch(error){setMsg(error.message||String(error))}finally{setBusy(false)}}
 async function openDetail(row,current){const codigo=clean(row?.code);if(!codigo)return;setEditor({row,value:clean(current),loading:true,saving:false,error:''});try{const result=await post('getComentarioAdminEstudiante',{codigo});setEditor(x=>x?{...x,value:clean(result.comentario_admin),loading:false}:x)}catch(error){setEditor(x=>x?{...x,loading:false,error:error.message||String(error)}:x)}}
 async function saveDetail(){if(!editor||editor.loading||editor.saving)return;const codigo=clean(editor.row?.code);setEditor(x=>({...x,saving:true,error:''}));try{const result=await post('guardarComentarioAdminEstudiante',{codigo,comentario:clean(editor.value)}),saved=clean(result.comentario_admin);setDetails(x=>({...x,[codigo]:saved}));setMsg(saved?'Seguimiento guardado y marcado como revisado.':'Seguimiento eliminado.');setEditor(null)}catch(error){setEditor(x=>x?{...x,saving:false,error:error.message||String(error)}:x)}}
 return{movements,all,financeMap,busy,msg,setMsg,details,editor,setEditor,query,setQuery,groupFilter,setGroupFilter,groupOptions,levelFilter,setLevelFilter,statusFilter,setStatusFilter,periodFilter,setPeriodFilter,whatsappFilter,setWhatsappFilter,sort,setSort,statusOptions,periodOptions,visible,pending,applied,originalPending,originalApplied,hasFilters,stats,onSort,clearFilters,refresh,refreshMora,openDetail,saveDetail};
}
Object.assign(N,{groupFallbackLabel,moraPeriod,applyMoraLive,useConapePanelData});
})();
