// F98.4-Z6-CS21A106 · Enlace académico por 6-historial oficial.
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const baseUse=N.useConapePanelData,{clean,levelId,filterRows,compareRows,uniqueSorted}=N,VALID=['B1','B2','I1','I2'];
function movementPeriod(month){const n=Number(month)||0;return n>=1&&n<=12?Math.ceil(n/4):0}
function historyCandidates(row){const year=Number(row?.year)||0,period=movementPeriod(row?.month),history=Array.isArray(row?.historySummary)?row.historySummary:[];return history.filter(item=>VALID.includes(clean(item?.level).toUpperCase())&&Number(item?.year)===year&&Number(item?.period)===period).slice().sort((a,b)=>Number(b?.sourceRow||0)-Number(a?.sourceRow||0))}
function resolveMovementAcademic(row){const current=levelId(row),candidates=historyCandidates(row);let match=null,source='';if(candidates.length===1){match=candidates[0];source='6_HISTORIAL_EXACT_PERIOD'}else if(candidates.length>1&&current){match=candidates.find(item=>clean(item?.level).toUpperCase()===current)||null;if(match)source='6_HISTORIAL_EXACT_PERIOD_AND_LEVEL'}if(!match&&VALID.includes(current)){const same=(Array.isArray(row?.historySummary)?row.historySummary:[]).filter(item=>clean(item?.level).toUpperCase()===current).sort((a,b)=>Number(b?.sourceRow||0)-Number(a?.sourceRow||0));match=same[0]||null;source=match?'BACKEND_LEVEL_CONFIRMED_BY_HISTORY':'BACKEND_LEVEL'}if(!match)return{...row,levelLinkSource:VALID.includes(current)?'BACKEND_LEVEL':'UNRESOLVED',levelLinked:VALID.includes(current),levelLinkAmbiguous:candidates.length>1,levelLinkCandidateCount:candidates.length};const level=clean(match.level).toUpperCase();return{...row,level,levelLabel:clean(match.levelLabel)||row.levelLabel,academicStatus:clean(match.status||row.academicStatus).toUpperCase(),periodType:clean(match.periodType||row.periodType).toUpperCase(),levelLinked:true,levelLinkSource:source,levelLinkSourceRow:Number(match.sourceRow)||0,levelLinkAmbiguous:false,levelLinkCandidateCount:candidates.length}}
function audit(rows){const list=Array.isArray(rows)?rows:[],exact=list.filter(r=>String(r?.levelLinkSource||'').startsWith('6_HISTORIAL_EXACT')).length,backend=list.filter(r=>String(r?.levelLinkSource||'').startsWith('BACKEND')).length,unresolved=list.filter(r=>!VALID.includes(levelId(r))).length;return{version:'F98.4-Z6-CS21A106',total:list.length,exactHistory:exact,backendFallback:backend,unresolved,allVisible:exact+backend+unresolved===list.length}}
function useConapePanelDataCS21A106(data,onRefresh){const s=baseUse(data,onRefresh),all=React.useMemo(()=>(s.all||[]).map(resolveMovementAcademic),[s.all]),filters={query:s.query,level:s.levelFilter,status:s.statusFilter,period:s.periodFilter,whatsapp:s.whatsappFilter},visible=React.useMemo(()=>filterRows(all,filters).filter(row=>s.groupFilter==='ALL'||clean(row?.group)===s.groupFilter).slice().sort((a,b)=>compareRows(a,b,s.sort)),[all,s.query,s.groupFilter,s.levelFilter,s.statusFilter,s.periodFilter,s.whatsappFilter,s.sort.key,s.sort.dir]),pending=visible.filter(r=>!r.appliedInSystem),applied=visible.filter(r=>r.appliedInSystem),originalPending=all.filter(r=>!r.appliedInSystem),originalApplied=all.filter(r=>r.appliedInSystem),statusOptions=React.useMemo(()=>uniqueSorted(all.map(r=>clean(r?.academicStatus||'SIN_ESTADO').toUpperCase())),[all]),linkAudit=React.useMemo(()=>audit(all),[all]),stats={...(s.stats||{}),levelLinked:all.filter(r=>VALID.includes(levelId(r))).length,unresolvedLevel:all.filter(r=>!VALID.includes(levelId(r))).length};try{window.__AN_CONAPE_LEVEL_LINK_AUDIT__=linkAudit}catch(_){}return{...s,all,visible,pending,applied,originalPending,originalApplied,statusOptions,stats,linkAudit}}
N.movementAcademicPeriod=movementPeriod;N.historyPeriodCandidates=historyCandidates;N.resolveMovementAcademic=resolveMovementAcademic;N.useConapePanelData=useConapePanelDataCS21A106;N.__LEVEL_LINK_BUILD__='F98.4-Z6-CS21A106';
})();
