// F98.4-Z6-CS21A109 · Panel completo, periodos B/C reales y multiorden estable.
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const BUILD='F98.4-Z6-CS21A109',SNAPSHOT_KEY='an_master_dashboard_snapshot_cs21a109',SYNC_KEY='an_master_conape_last_sync_cs21a98',SYNC_MS=30*60*1000;
const{clean,levelId,injectStyles,useConapePanelData:baseUseConapePanelData,useConapeReview,PanelView,filterRows,compareRowsMulti,uniqueSorted,normalizeSortStack,historyPeriodCandidates}=N,VALID=['B1','B2','I1','I2'];
function resolveMovement(row){const current=levelId(row),history=Array.isArray(row?.historySummary)?row.historySummary:[],candidates=historyPeriodCandidates(row),currentMatch=VALID.includes(current)?candidates.find(item=>clean(item?.level).toUpperCase()===current):null,levels=Array.from(new Set(candidates.map(item=>clean(item?.level).toUpperCase()).filter(level=>VALID.includes(level))));let match=currentMatch||null,source=currentMatch?'6_HISTORIAL_EXACT_PERIOD_AND_LEVEL':'';if(!match&&levels.length===1){match=candidates.find(item=>clean(item?.level).toUpperCase()===levels[0])||candidates[0];source='6_HISTORIAL_EXACT_PERIOD'}if(!match&&VALID.includes(current)){match=history.filter(item=>clean(item?.level).toUpperCase()===current).sort((a,b)=>Number(b?.sourceRow||0)-Number(a?.sourceRow||0))[0]||null;source=match?'BACKEND_LEVEL_CONFIRMED_BY_HISTORY':'BACKEND_LEVEL'}if(!match)return{...row,level:'UNRESOLVED',levelLabel:'Nivel por confirmar',academicStatus:clean(row?.academicStatus||'SIN_ENLACE').toUpperCase(),levelLinkSource:'UNRESOLVED',levelLinked:false};const level=clean(match.level).toUpperCase();return{...row,level,levelLabel:clean(match.levelLabel)||row.levelLabel,academicStatus:clean(match.status||row.academicStatus).toUpperCase(),periodType:clean(match.periodType||match.tipoPeriodo||match.tipo_periodo||row.periodType).toUpperCase(),academicPeriod:Number(match.period)||row.academicPeriod,levelLinked:true,levelLinkSource:source,levelLinkSourceRow:Number(match.sourceRow)||0}}
function useConapePanelDataCS21A109(data,onRefresh){const s=baseUseConapePanelData(data,onRefresh),all=React.useMemo(()=>(s.all||[]).map(resolveMovement),[s.all]),filters={query:s.query,level:s.levelFilter==='SIN_NIVEL'?'ALL':s.levelFilter,status:s.statusFilter,period:s.periodFilter,whatsapp:s.whatsappFilter},sortStack=normalizeSortStack(s.sortStack),visible=React.useMemo(()=>filterRows(all,filters).filter(row=>(s.levelFilter!=='SIN_NIVEL'||levelId(row)==='UNRESOLVED')&&(s.groupFilter==='ALL'||clean(row?.group)===s.groupFilter)).slice().sort((a,b)=>compareRowsMulti(a,b,sortStack)),[all,s.query,s.groupFilter,s.levelFilter,s.statusFilter,s.periodFilter,s.whatsappFilter,JSON.stringify(sortStack)]),pending=visible.filter(r=>!r.appliedInSystem),applied=visible.filter(r=>r.appliedInSystem),originalPending=all.filter(r=>!r.appliedInSystem),originalApplied=all.filter(r=>r.appliedInSystem),statusOptions=React.useMemo(()=>uniqueSorted(all.map(r=>clean(r?.academicStatus||'SIN_ESTADO').toUpperCase())),[all]),stats={...(s.stats||{}),levelLinked:all.filter(r=>VALID.includes(levelId(r))).length,unresolvedLevel:all.filter(r=>levelId(r)==='UNRESOLVED').length},audit={version:BUILD,total:all.length,exactHistory:all.filter(r=>String(r?.levelLinkSource||'').startsWith('6_HISTORIAL_EXACT')).length,backendFallback:all.filter(r=>String(r?.levelLinkSource||'').startsWith('BACKEND')).length,unresolved:all.filter(r=>levelId(r)==='UNRESOLVED').length,bimestral:all.filter(r=>clean(r?.periodType).toUpperCase()==='B').length,cuatrimestral:all.filter(r=>clean(r?.periodType).toUpperCase()==='C').length,allVisible:all.every(r=>!!levelId(r))};try{window.__AN_CONAPE_LEVEL_LINK_AUDIT__=audit}catch(_){}return{...s,all,visible,pending,applied,originalPending,originalApplied,statusOptions,stats,sortStack,linkAudit:audit}}
function MasterConapeMovementsTableCS21A109({data,onRefresh}){injectStyles();const d=useConapePanelDataCS21A109(data,onRefresh),r=useConapeReview(d.all,d.setMsg),scopedData={...data,conapeAutoSync:{...(data?.conapeAutoSync||{}),movimientos_registrados:d.originalPending.length,nuevos:d.originalPending.length,scope:'ACADEMIC_DISBURSEMENT_01_ONLY'}};const filterState={query:d.query,setQuery:d.setQuery,groupFilter:d.groupFilter,setGroupFilter:d.setGroupFilter,levelFilter:d.levelFilter,setLevelFilter:d.setLevelFilter,statusFilter:d.statusFilter,setStatusFilter:d.setStatusFilter,periodFilter:d.periodFilter,setPeriodFilter:d.setPeriodFilter,whatsappFilter:d.whatsappFilter,setWhatsappFilter:d.setWhatsappFilter,sortStack:d.sortStack,setSortStack:d.setSortStack,hasFilters:d.hasFilters,clearFilters:d.clearFilters},tableProps={details:d.details,openDetail:d.openDetail,financeMap:d.financeMap,sortStack:d.sortStack,onSort:d.onSort,reviewSteps:r.reviewSteps,onReview:r.saveReview,reviewBusy:r.reviewBusy};return <PanelView BUILD={BUILD} data={scopedData} movements={d.movements} busy={d.busy} msg={d.msg} refresh={d.refresh} originalPending={d.originalPending} originalApplied={d.originalApplied} stats={d.stats} visible={d.visible} all={d.all} pending={d.pending} applied={d.applied} hasFilters={d.hasFilters} filterState={filterState} options={{groups:d.groupOptions,status:d.statusOptions,period:d.periodOptions}} tableProps={tableProps} editor={d.editor} setEditor={d.setEditor} saveDetail={d.saveDetail}/>} 
MasterConapeMovementsTableCS21A109.__anFullConapePanel=true;MasterConapeMovementsTableCS21A109.__anBuild=BUILD;
function readSnapshot(){try{const x=JSON.parse(sessionStorage.getItem(SNAPSHOT_KEY)||'null');return x&&x.data?.ok&&Date.now()-Number(x.savedAt||0)<10*60*1000?x:null}catch(_){return null}}
function saveSnapshot(data){try{sessionStorage.setItem(SNAPSHOT_KEY,JSON.stringify({savedAt:Date.now(),data}))}catch(_){} }
function syncAge(){try{return Date.now()-Number(localStorage.getItem(SYNC_KEY)||0)}catch(_){return SYNC_MS}}
function markSync(){try{localStorage.setItem(SYNC_KEY,String(Date.now()))}catch(_){} }
function useMasterDataCS21A109(){const initial=React.useMemo(readSnapshot,[]),[state,setState]=React.useState({loading:!initial,error:'',data:initial?.data||null}),running=React.useRef(false),syncing=React.useRef(false),alive=React.useRef(true),timer=React.useRef(null);const load=React.useCallback(async({refresh=false,silent=false}={})=>{if(running.current)return;running.current=true;if(!silent)setState(x=>({...x,loading:true,error:''}));const started=performance.now();try{const dashboard=await window.masterPost({refresh});if(!dashboard?.ok)throw Error(dashboard?.mensaje||dashboard?.error||'No se pudo cargar');if(alive.current){saveSnapshot(dashboard);window.__AN_MASTER_LAST_LOAD__={ms:Math.round(performance.now()-started),source:dashboard?.performance?.source||dashboard?.cache_layer||(dashboard?.cache?'cache':'backend')};setState({loading:false,error:'',data:dashboard})}}catch(error){if(alive.current)setState(x=>({loading:false,error:error?.message||String(error),data:x.data}))}finally{running.current=false}},[]);const sync=React.useCallback(async(force=false)=>{if(syncing.current||(!force&&syncAge()<SYNC_MS))return;syncing.current=true;try{await window.masterAction('actualizarPanelConapeAhora');markSync();await load({refresh:true,silent:true})}catch(_){}finally{syncing.current=false}},[load]);React.useEffect(()=>{alive.current=true;load({refresh:false,silent:!!initial});const schedule=()=>{clearTimeout(timer.current);timer.current=setTimeout(async()=>{await sync(false);schedule()},Math.max(1200,SYNC_MS-Math.min(SYNC_MS,syncAge())))};schedule();const focus=()=>{if(syncAge()>=SYNC_MS)sync(false)};window.addEventListener('focus',focus);return()=>{alive.current=false;clearTimeout(timer.current);window.removeEventListener('focus',focus)}},[]);return{...state,refetch:async()=>{await sync(true);await load({refresh:true})}}}
function dependenciesReady(){return typeof N.PanelView==='function'&&typeof N.useConapeReview==='function'&&typeof baseUseConapePanelData==='function'&&typeof window.MasterConapeMovementsTable==='function'}
function install(){if(!dependenciesReady())return false;window.MasterConapeMovementsTable=MasterConapeMovementsTableCS21A109;try{MasterConapeMovementsTable=MasterConapeMovementsTableCS21A109}catch(_){}window.useMasterData=useMasterDataCS21A109;try{useMasterData=useMasterDataCS21A109}catch(_){}window.__AN_MASTER_CONAPE_MOVEMENTS_BUILD__=BUILD;window.__AN_MASTER_PERFORMANCE_BUILD__=BUILD;window.__AN_MASTER_CONAPE_FULL_PANEL_ACTIVE__=window.MasterConapeMovementsTable===MasterConapeMovementsTableCS21A109;return window.__AN_MASTER_CONAPE_FULL_PANEL_ACTIVE__}
function installBurst(){[0,20,60,120,250,500,900,1500,2500,4000].forEach(delay=>window.setTimeout(install,delay))}
N.resolveMovementAcademicCS21A109=resolveMovement;N.useConapePanelDataCS21A109=useConapePanelDataCS21A109;N.MasterConapeMovementsTableCS21A109=MasterConapeMovementsTableCS21A109;N.installMasterConapePanelCS21A109=install;
window.addEventListener('an:lazy-module-loaded',installBurst);window.addEventListener('focus',installBurst);document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')installBurst()});installBurst();
const probe=window.setInterval(install,200);window.setTimeout(()=>window.clearInterval(probe),90000);
})();
