// F98.4-Z6-CS21A109 · Periodos B/C reales, morosidad correcta y multiorden.
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const{clean,levelId,isAcademicDisbursement01,post,masterConapeSafeUserError,uniqueSorted,dedupeMovementRows,filterRows,compareRowsMulti,normalizeSortStack}=N;
function groupFallbackLabel(row){
 const code=clean(row?.group||row?.code),parts=code.split('-'),slot=parts[1]||'',dayCode=slot.replace(/\d/g,''),timeCode=slot.replace(/\D/g,''),days={LM:'LUNES Y MIÉRCOLES',KJ:'MARTES Y JUEVES',LJ:'LUNES A JUEVES',SA:'SÁBADO'}[dayCode]||clean(row?.groupDays)||dayCode||'DÍAS SIN DEFINIR',schedule=clean(row?.groupSchedule)||({69:'6-9 PM',94:'9 AM-4 PM'}[timeCode]||timeCode),teacher=clean(row?.groupTeacher)||'DOCENTE SIN ASIGNAR',consecutive=clean(row?.groupConsecutive)||parts[parts.length-1]||code;
 return[teacher,`${days}${schedule?` ${schedule}`:''}`,consecutive].filter(Boolean).join(' - ');
}
function periodType(value){const t=clean(value).toUpperCase();if(t.startsWith('B'))return'B';if(t.startsWith('C'))return'C';if(t.startsWith('S'))return'S';if(t.startsWith('M'))return'M';return t}
function periodForType(month,type){const m=Number(month)||0,t=periodType(type);if(m<1||m>12)return 0;if(t==='B')return Math.ceil(m/2);if(t==='C')return Math.ceil(m/4);if(t==='S')return Math.ceil(m/6);if(t==='M')return m;return 0}
function historyPeriodCandidates(row){const year=Number(row?.year)||0,month=Number(row?.month)||0,history=Array.isArray(row?.historySummary)?row.historySummary:[];return history.filter(item=>{const itemYear=Number(item?.year)||0,itemPeriod=Number(item?.period)||0,type=item?.periodType||item?.tipoPeriodo||item?.tipo_periodo||row?.periodType;return itemYear===year&&itemPeriod>0&&periodForType(month,type)===itemPeriod}).sort((a,b)=>Number(b?.sourceRow||0)-Number(a?.sourceRow||0))}
function academicPeriodForMovement(row){const candidates=historyPeriodCandidates(row),current=levelId(row);const exact=candidates.find(item=>clean(item?.level).toUpperCase()===current)||candidates[0];if(exact)return Number(exact.period)||0;const explicitType=row?.periodType||row?.tipoPeriodo||row?.tipo_periodo,derived=periodForType(row?.month,explicitType);return derived||Math.ceil((Number(row?.month)||0)/4)}
function moraPeriod(value,type){return value&&typeof value==='object'?academicPeriodForMovement(value):periodForType(value,type||'C')}
function applyMoraLive(row,live){
 if(!live)return row;
 const state=clean(live.state||'SIN_FILA').toUpperCase(),applied=state==='NO',resolvedPeriod=Number(live.period)||academicPeriodForMovement(row);
 return{...row,moraState:state,mora:state==='SI',moraPeriod:resolvedPeriod,moraYear:Number(live.year)||Number(row.year)||0,moraRowCount:Number(live.count)||0,moraSourceRows:Array.isArray(live.rows)?live.rows:[],moraSourceId:live.sourceId||row.moraSourceId,moraSourceSheet:live.sourceSheet||row.moraSourceSheet,moraVerifiedLive:true,appliedInSystem:applied,applicationState:applied?'APLICADO_EN_SISTEMA':(state==='SI'?'PENDIENTE_MOROSIDAD_SI':'PENDIENTE_SIN_FILA_MOROSIDAD'),followupClosed:applied,followupState:applied?'DESEMBOLSO_01_CERRADO':'DESEMBOLSO_01_PENDIENTE',reviewStep:applied?0:row.reviewStep,reviewClosedReset:applied,applicationBasis:`LIVE_7_MOROSIDAD_${state}`};
}
function useConapePanelData(data,onRefresh){
 const movements=data?.conape?.movements||{},baseRows=React.useMemo(()=>dedupeMovementRows((Array.isArray(movements.rows)?movements.rows:[]).filter(isAcademicDisbursement01)),[data]),financeRows=Array.isArray(data?.collections?.rows)?data.collections.rows:[];
 const[moraLive,setMoraLive]=React.useState({}),[busy,setBusy]=React.useState(false),[msg,setMsg]=React.useState(''),[details,setDetails]=React.useState({}),[editor,setEditor]=React.useState(null),[query,setQuery]=React.useState(''),[groupFilter,setGroupFilter]=React.useState('ALL'),[levelFilter,setLevelFilter]=React.useState('ALL'),[statusFilter,setStatusFilter]=React.useState('ALL'),[periodFilter,setPeriodFilter]=React.useState('ALL'),[whatsappFilter,setWhatsappFilter]=React.useState('ALL'),[sortStack,setSortStackState]=React.useState([{key:'disbursement',dir:'asc'},{key:'code',dir:'asc'}]);
 const all=React.useMemo(()=>baseRows.map(row=>applyMoraLive(row,moraLive[row.id])),[baseRows,moraLive]);
 const liveRef=React.useRef(false),rowsRef=React.useRef(baseRows);rowsRef.current=baseRows;
 const refreshMora=React.useCallback(async(silent=true)=>{if(liveRef.current||!rowsRef.current.length)return;liveRef.current=true;try{const items=rowsRef.current.map(row=>({id:row.id,cedula:row.cedula,year:row.year,month:row.month,period:academicPeriodForMovement(row)})),result=await post('getConapeMoraStates',{items}),next={};(result.items||[]).forEach(item=>{if(item?.id)next[item.id]=item});setMoraLive(next);if(!silent)setMsg('Morosidad verificada directamente en 7-morosidad oficial.')}catch(error){if(!silent)setMsg(masterConapeSafeUserError(error?.message||String(error),'No se pudo verificar la morosidad. Intentá de nuevo.','verificar_morosidad'))}finally{liveRef.current=false}},[]);
 React.useEffect(()=>{let active=true;const run=()=>{if(active&&document.visibilityState!=='hidden')refreshMora(true)};run();const timer=setInterval(run,20000),focus=()=>refreshMora(true);window.addEventListener('focus',focus);return()=>{active=false;clearInterval(timer);window.removeEventListener('focus',focus)}},[refreshMora,baseRows]);
 const financeMap=React.useMemo(()=>{const out={},by={};financeRows.forEach(x=>{const c=clean(x?.code),l=clean(x?.level).toUpperCase();if(!c)return;if(l)out[`${c}|${l}`]=x;(by[c]||(by[c]=[])).push(x)});Object.keys(by).forEach(c=>{if(by[c].length===1)out[c]=by[c][0]});return out},[data]);
 React.useEffect(()=>{const next={};all.forEach(row=>{const c=clean(row?.code);if(c)next[c]=clean(row?.detail)});setDetails(next)},[all]);
 const groupOptions=React.useMemo(()=>{const map=new Map();(Array.isArray(movements.groupOptions)?movements.groupOptions:[]).forEach(item=>{const code=clean(item?.code);if(code)map.set(code,{code,label:clean(item?.label)||groupFallbackLabel({...item,group:code})})});all.forEach(row=>{const code=clean(row?.group);if(code&&!map.has(code))map.set(code,{code,label:clean(row?.groupLabel)||groupFallbackLabel(row)})});return Array.from(map.values()).sort((a,b)=>String(a.label||a.code).localeCompare(String(b.label||b.code),'es',{numeric:true,sensitivity:'base'}))},[data,all]);
 React.useEffect(()=>{if(groupFilter!=='ALL'&&!groupOptions.some(x=>x.code===groupFilter))setGroupFilter('ALL')},[groupOptions,groupFilter]);
 const statusOptions=React.useMemo(()=>uniqueSorted(all.map(r=>clean(r?.academicStatus||'SIN_ESTADO').toUpperCase())),[all]),periodOptions=React.useMemo(()=>uniqueSorted(all.map(r=>`${String(r?.month||0).padStart(2,'0')}/${r?.year||0}`)),[all]);
 const normalizedSort=normalizeSortStack(sortStack),filters={query,level:levelFilter,status:statusFilter,period:periodFilter,whatsapp:whatsappFilter},visible=React.useMemo(()=>filterRows(all,filters).filter(row=>groupFilter==='ALL'||clean(row?.group)===groupFilter).slice().sort((a,b)=>compareRowsMulti(a,b,normalizedSort)),[all,query,groupFilter,levelFilter,statusFilter,periodFilter,whatsappFilter,JSON.stringify(normalizedSort)]),pending=visible.filter(r=>!r.appliedInSystem),applied=visible.filter(r=>r.appliedInSystem),originalPending=all.filter(r=>!r.appliedInSystem),originalApplied=all.filter(r=>r.appliedInSystem),hasFilters=!!query||groupFilter!=='ALL'||levelFilter!=='ALL'||statusFilter!=='ALL'||periodFilter!=='ALL'||whatsappFilter!=='ALL',stats={mora:all.filter(r=>r.moraState==='SI').length,levelLinked:all.filter(r=>['B1','B2','I1','I2'].includes(levelId(r))).length,unlinked:all.filter(r=>!r.linked).length};
 function setSortStack(next){setSortStackState(normalizeSortStack(typeof next==='function'?next(normalizedSort):next))}
 function setSort(next){setSortStack(current=>[next,...current.filter(item=>item.key!==next.key)].slice(0,3))}
 function onSort(key){setSortStack(current=>{const first=current[0]||{key:'disbursement',dir:'asc'},dir=first.key===key&&first.dir==='asc'?'desc':'asc';return[{key,dir},...current.filter(item=>item.key!==key)].slice(0,3)})}
 function clearFilters(){setQuery('');setGroupFilter('ALL');setLevelFilter('ALL');setStatusFilter('ALL');setPeriodFilter('ALL');setWhatsappFilter('ALL')}
 async function refresh(){setBusy(true);setMsg('');try{const result=await window.masterAction('actualizarPanelConapeAhora');await onRefresh?.();await refreshMora(false);setMsg(result.mensaje||'CONAPE y morosidad oficial actualizados.')}catch(error){setMsg(masterConapeSafeUserError(error?.message||String(error),'No se pudo actualizar el panel CONAPE. Intentá de nuevo.','actualizar_panel'))}finally{setBusy(false)}}
 async function openDetail(row,current){const codigo=clean(row?.code);if(!codigo)return;setEditor({row,value:clean(current),loading:true,saving:false,error:''});try{const result=await post('getComentarioAdminEstudiante',{codigo});setEditor(x=>x?{...x,value:clean(result.comentario_admin),loading:false}:x)}catch(error){setEditor(x=>x?{...x,loading:false,error:masterConapeSafeUserError(error?.message||String(error),'No se pudo cargar el seguimiento. Intentá de nuevo.','cargar_seguimiento')}:x)}}
 async function saveDetail(){if(!editor||editor.loading||editor.saving)return;const codigo=clean(editor.row?.code);setEditor(x=>({...x,saving:true,error:''}));try{const result=await post('guardarComentarioAdminEstudiante',{codigo,comentario:clean(editor.value)}),saved=clean(result.comentario_admin);setDetails(x=>({...x,[codigo]:saved}));setMsg(saved?'Seguimiento guardado y marcado como revisado.':'Seguimiento eliminado.');setEditor(null)}catch(error){setEditor(x=>x?{...x,saving:false,error:masterConapeSafeUserError(error?.message||String(error),'No se pudo guardar el seguimiento. Intentá de nuevo.','guardar_seguimiento')}:x)}}
 return{movements,all,financeMap,busy,msg,setMsg,details,editor,setEditor,query,setQuery,groupFilter,setGroupFilter,groupOptions,levelFilter,setLevelFilter,statusFilter,setStatusFilter,periodFilter,setPeriodFilter,whatsappFilter,setWhatsappFilter,sort:normalizedSort[0],setSort,sortStack:normalizedSort,setSortStack,statusOptions,periodOptions,visible,pending,applied,originalPending,originalApplied,hasFilters,stats,onSort,clearFilters,refresh,refreshMora,openDetail,saveDetail};
}
Object.assign(N,{groupFallbackLabel,periodType,periodForType,historyPeriodCandidates,academicPeriodForMovement,moraPeriod,applyMoraLive,useConapePanelData});
})();
