// F98.4-Z6-CS21A109 · Orden múltiple canónico del Panel Maestro CONAPE.
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const {clean,normalize,phone,levelId,LEVEL_ORDER,STATUS_ORDER,LEVEL,fullDate,DetailModal,studentGroupCount}=N;
const baseSortValue=typeof N.sortValue==='function'?N.sortValue:null;
const SORT_OPTIONS=[
 ['disbursement:asc','Fecha desembolso · más antigua'],['disbursement:desc','Fecha desembolso · más reciente'],
 ['group:asc','Grupo · A–Z'],['group:desc','Grupo · Z–A'],
 ['code:asc','Código · menor a mayor'],['code:desc','Código · mayor a menor'],
 ['detected:desc','Detectado · más reciente'],['detected:asc','Detectado · más antiguo'],
 ['student:asc','Estudiante · A–Z'],['student:desc','Estudiante · Z–A'],
 ['academic:asc','Ruta académica'],['whatsapp:asc','WhatsApp disponible primero']
];
function dateValue(value){if(value instanceof Date&&!Number.isNaN(value.getTime()))return value.getTime();if(typeof value==='number'&&Number.isFinite(value))return value;const s=clean(value);let m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})/);if(m)return Date.UTC(Number(m[3]),Number(m[2])-1,Number(m[1]));m=s.match(/^(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);if(m)return Date.UTC(Number(m[1]),Number(m[2])-1,Number(m[3]));const d=new Date(s);return Number.isNaN(d.getTime())?0:d.getTime()}
function disbursementDateValue(row){const direct=row?.eventDate||row?.fechaRaw||row?.FECHA_RAW||row?.disbursementDate||row?.date;const parsed=dateValue(direct);if(parsed)return parsed;const year=Number(row?.year)||0,month=Number(row?.month)||0;return year&&month?Date.UTC(year,month-1,1):0}
function sortValueMulti(row,key){if(key==='disbursement'||key==='period')return disbursementDateValue(row);if(key==='group')return normalize(row?.groupLabel||row?.group);if(key==='code'){const n=Number(clean(row?.code).replace(/\D/g,''));return Number.isFinite(n)&&n>0?n:clean(row?.code)}if(key==='student')return normalize(row?.name);if(key==='detected')return Number(row?.detectedSort||dateValue(row?.detectedAt)||0);if(key==='academic')return(LEVEL_ORDER[levelId(row)]||99)*100+(STATUS_ORDER[clean(row?.academicStatus).toUpperCase()]||90);if(key==='whatsapp')return row?.appliedInSystem?2:(phone(row?.phone)?0:1);return baseSortValue?baseSortValue(row,key):0}
function normalizeSortStack(stack){const source=Array.isArray(stack)?stack:[],out=[],seen=new Set();source.forEach(item=>{const key=clean(item?.key),dir=item?.dir==='desc'?'desc':'asc';if(!key||seen.has(key)||out.length>=3)return;seen.add(key);out.push({key,dir})});if(!out.length)out.push({key:'disbursement',dir:'asc'},{key:'code',dir:'asc'});return out}
function compareCriterion(a,b,criterion){const av=sortValueMulti(a,criterion.key),bv=sortValueMulti(b,criterion.key),cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'es',{numeric:true,sensitivity:'base'});return criterion.dir==='desc'?-cmp:cmp}
function compareRowsMulti(a,b,stack){for(const criterion of normalizeSortStack(stack)){const cmp=compareCriterion(a,b,criterion);if(cmp!==0)return cmp}const codeCmp=compareCriterion(a,b,{key:'code',dir:'asc'});if(codeCmp!==0)return codeCmp;return Number(b?.detectedSort||0)-Number(a?.detectedSort||0)}
function injectStyles(){if(document.getElementById('an-master-conape-multisort-cs21a109'))return;const style=document.createElement('style');style.id='an-master-conape-multisort-cs21a109';style.textContent='.master-conape-group-filter{grid-column:span 2;min-width:320px}.master-conape-group-filter select{font-size:9.5px}.master-conape-sort-priorities{grid-column:1/-1;display:grid;grid-template-columns:repeat(3,minmax(210px,1fr));gap:10px;padding-top:2px}.master-conape-sort-priorities label{min-width:0}.master-conape-sort-priorities select{width:100%}@media(max-width:900px){.master-conape-group-filter{grid-column:1/-1;min-width:0}.master-conape-sort-priorities{grid-template-columns:1fr}}';document.head.appendChild(style)}
function updateSortPriority(stack,index,value){let next=normalizeSortStack(stack);if(!value){next.splice(index,1);return normalizeSortStack(next)}const[key,dir]=value.split(':');next=next.filter((item,i)=>i===index||item.key!==key);next[index]={key,dir};return normalizeSortStack(next.filter(Boolean))}
function SortPriority({index,stack,setStack}){const normalized=normalizeSortStack(stack),item=normalized[index],value=item?`${item.key}:${item.dir}`:'';return <label><span>Orden {index+1}</span><select value={value} onChange={e=>setStack(updateSortPriority(normalized,index,e.target.value))}>{index>0&&<option value="">Sin otra prioridad</option>}{SORT_OPTIONS.map(([v,label])=><option key={v} value={v}>{label}</option>)}</select></label>}
function Filters({state,options}){injectStyles();const{query,setQuery,groupFilter,setGroupFilter,levelFilter,setLevelFilter,statusFilter,setStatusFilter,periodFilter,setPeriodFilter,whatsappFilter,setWhatsappFilter,sortStack,setSortStack,hasFilters,clearFilters}=state;return <div className="master-conape-controls"><label className="master-conape-search"><span>Buscar estudiante</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Código, cédula, teléfono o nombre"/></label><label className="master-conape-group-filter"><span>Grupo</span><select value={groupFilter} onChange={e=>setGroupFilter(e.target.value)} title="Filtrar por grupo académico"><option value="ALL">Todos los grupos</option>{options.groups.map(item=><option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label><span>Nivel</span><select value={levelFilter} onChange={e=>setLevelFilter(e.target.value)}><option value="ALL">Todos</option>{Object.keys(LEVEL).map(v=><option key={v} value={v}>{v} · {LEVEL[v]}</option>)}<option value="SIN_NIVEL">Sin nivel enlazado</option></select></label><label><span>Resumen académico</span><select value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="ALL">Todos</option>{options.status.map(v=><option key={v} value={v}>{v==='SIN_ESTADO'?'Sin estado':v}</option>)}</select></label><label><span>Periodo</span><select value={periodFilter} onChange={e=>setPeriodFilter(e.target.value)}><option value="ALL">Todos</option>{options.period.map(v=><option key={v} value={v}>{v}</option>)}</select></label><label><span>WhatsApp</span><select value={whatsappFilter} onChange={e=>setWhatsappFilter(e.target.value)}><option value="ALL">Todos</option><option value="AVAILABLE">Disponible para enviar</option><option value="MISSING">Sin teléfono</option><option value="CLOSED">Cerrados</option></select></label><div className="master-conape-sort-priorities"><SortPriority index={0} stack={sortStack} setStack={setSortStack}/><SortPriority index={1} stack={sortStack} setStack={setSortStack}/><SortPriority index={2} stack={sortStack} setStack={setSortStack}/></div>{hasFilters&&<button type="button" className="master-conape-clear" onClick={clearFilters}>Limpiar filtros</button>}</div>}
function plural(n,one,many){return`${n} ${n===1?one:many}`}
function PanelView(p){const{BUILD,data,movements,busy,msg,refresh,originalPending,originalApplied,stats,visible,all,pending,applied,hasFilters,filterState,options,tableProps,editor,setEditor,saveDetail}=p,visibleStudents=studentGroupCount(visible),allStudents=studentGroupCount(all),appliedStudents=studentGroupCount(applied),originalAppliedStudents=studentGroupCount(originalApplied),Table=N.Table;return <section className="master-card master-conape-month-card" data-build={BUILD}><header><div><span>Seguimiento inmediato</span><h3>Desembolsos académicos 01 · pendientes primero</h3><p>Una ficha por estudiante · movimientos alineados por nivel · última lectura {fullDate(movements.lastSync)}</p></div><div className="master-conape-month-actions"><span className="master-live-chip on">Actualización automática · 30 min</span><button onClick={refresh} disabled={busy}>{busy?'Consultando…':'↻ Actualizar CONAPE ahora'}</button></div></header><div className="master-conape-month-kpis"><div><b>{originalPending.length}</b><span>01 pendientes</span></div><div><b>{originalApplied.length}</b><span>01 cerrados</span></div><div><b>{stats.mora}</b><span>morosos</span></div><div><b>{stats.levelLinked}</b><span>nivel enlazado</span></div><div><b>{stats.unlinked}</b><span>por vincular</span></div><div><b>{Math.max(0,Number(data?.conapeAutoSync?.movimientos_registrados??data?.conapeAutoSync?.nuevos??0)||0)}</b><span>nuevos detectados</span></div></div><Filters state={filterState} options={options}/><div className="master-conape-result-count"><span><strong>{visibleStudents}</strong> de {allStudents} estudiantes visibles</span><span>{plural(visible.length,'movimiento','movimientos')} académicos 01 · orden por hasta tres prioridades.</span></div>{msg&&<div className="master-conape-month-msg">{msg}</div>}<Table items={pending} empty={hasFilters?'No hay pendientes que coincidan con los filtros.':'No quedan desembolsos académicos 01 pendientes según 7-morosidad.'} {...tableProps}/><details className="master-conape-applied"><summary>✓ Desembolsos académicos 01 cerrados ({plural(appliedStudents,'estudiante','estudiantes')}{hasFilters?` de ${originalAppliedStudents}`:''} · {plural(applied.length,'movimiento','movimientos')})</summary><Table items={applied} empty={hasFilters?'No hay cerrados que coincidan con los filtros.':'Todavía no hay desembolsos académicos 01 cerrados.'} {...tableProps}/></details><DetailModal editor={editor} setEditor={setEditor} onSave={saveDetail}/></section>}
Object.assign(N,{dateValue,disbursementDateValue,sortValueMulti,normalizeSortStack,compareRowsMulti,SORT_OPTIONS,updateSortPriority,SortPriority,Filters,PanelView});
})();
