// F98.4-Z6-CS21A42 · Estado con lectura real y sin recarga total.
(function(){'use strict';
const BUILD='F98.4-Z6-CS21A42',NEXT={B1:'B2',B2:'I1',I1:'I2'},LABEL={B1:'Básico I',B2:'Básico II',I1:'Intermedio I',I2:'Intermedio II'};
async function call(fn,p={},timeout=100000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(`${window.APPS_SCRIPT_URL}?fn=${encodeURIComponent(fn)}`,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({fn,token:window.getSessionToken?.()||'',...p}),cache:'no-store',signal:c.signal}),x=await r.text();let d;try{d=JSON.parse(x)}catch(_){throw Error('Respuesta inválida de Apps Script.')}if(!r.ok||d?.ok!==true)throw Error(d?.error||d?.mensaje||'No se pudo completar la operación.');return d}finally{clearTimeout(t)}}
function Modal({estudiante,nivel,onClose,onSuccess}){const actual=String(estudiante?.estatus||'CA').toUpperCase(),codigo=String(estudiante?.codigo||estudiante?.rec_m||''),grupo=String(estudiante?.grupo||''),nv=String(nivel||'').toUpperCase(),sig=NEXT[nv]||'';
 const [nuevo,setNuevo]=React.useState(actual),[busy,setBusy]=React.useState(''),[next,setNext]=React.useState(null),[choice,setChoice]=React.useState(''),[error,setError]=React.useState(''),[saved,setSaved]=React.useState(null),promo=actual==='CA'&&nuevo==='APR';
 React.useEffect(()=>{let live=true;setNext(null);setChoice('');if(!promo||!sig)return()=>{live=false};setBusy('check');call('getEstudianteFresh',{codigo,consulta_en:Date.now()},50000).then(f=>{if(live){const i=f?.niveles?.[sig]||{};setNext({estatus:String(i.estatus||'SIN REGISTRO').toUpperCase(),grupo:String(i.grupo||grupo)})}}).catch(e=>live&&setError(e.message)).finally(()=>live&&setBusy(''));return()=>{live=false}},[promo,sig,codigo,grupo]);
 const estado=String(next?.estatus||''),pregunta=promo&&sig&&['PE','SIN REGISTRO'].includes(estado);
 async function fresh(result){setBusy('fresh');setError('');try{const ficha=await call('getEstudianteFresh',{codigo,nocache:true,consulta_en:Date.now()});onSuccess?.({...result,ficha_fresh:ficha,lectura_fresca:true});onClose?.()}catch(e){setError('El cambio quedó guardado, pero la ficha real no pudo cargarse: '+e.message);setBusy('')}}
 async function save(){if(nuevo===actual)return onClose?.();if(pregunta&&!choice)return setError('Indicá si también querés activar o crear el siguiente nivel.');setBusy('save');setError('');try{const d=await call(promo?'actualizarEstatusPromocionSegura':'actualizarEstatus',{codigo,cod_estudiante:codigo,nivel:nv,estatus:nuevo,nota:estudiante?.nota??null,grupo,activar_siguiente:pregunta&&choice==='SI',crear_siguiente:estado==='SIN REGISTRO'&&choice==='SI',siguiente_nivel:sig,siguiente_grupo:next?.grupo||grupo});setSaved(d);if(d.conape_sync===false){setBusy('conape');return}await fresh(d)}catch(e){setError(e.message);setBusy('')}}
 const msg=busy==='check'?'Verificando siguiente nivel…':busy==='save'?'Guardando en ESTATUS…':busy==='fresh'?'Reconstruyendo ficha real…':'';
 return <div style={{position:'fixed',inset:0,zIndex:10000,background:'#00153088',display:'flex',alignItems:'center',justifyContent:'center',padding:18}}><div style={{width:'min(580px,96vw)',background:'#fff',borderRadius:16,overflow:'hidden',boxShadow:'0 24px 70px #0005'}}><div style={{padding:'16px 19px',background:'#0d2b51',color:'#fff'}}><small>Consulta individual</small><h3 style={{margin:'3px 0'}}>Cambiar estatus · {LABEL[nv]||nv}</h3><div>{estudiante?.display||codigo} · actual <b>{actual}</b></div></div><div style={{padding:18}}><div style={{display:'flex',gap:7,flexWrap:'wrap',marginBottom:14}}>{['CA','APR','REP','CNV','RI','RJ','PE'].map(s=><button key={s} disabled={!!busy} onClick={()=>setNuevo(s)} style={{padding:'8px 12px',borderRadius:8,border:`2px solid ${nuevo===s?'#002f6c':'#d7dde5'}`,background:nuevo===s?'#002f6c':'#fff',color:nuevo===s?'#fff':'#26364d',fontWeight:900}}>{s}</button>)}</div>{promo&&sig&&<div style={{padding:12,borderRadius:10,background:'#eef4ff',border:'1px solid #c9d9f1',marginBottom:12}}><b>Promoción académica</b><p>{estado==='PE'?`¿Activar también ${LABEL[sig]}?`:estado==='SIN REGISTRO'?`¿Crear y activar ${LABEL[sig]}?`:`Siguiente nivel: ${estado||'verificando…'}`}</p>{pregunta&&<div style={{display:'flex',gap:8}}><button onClick={()=>setChoice('SI')}>Sí</button><button onClick={()=>setChoice('NO')}>No</button></div>}</div>}{msg&&<div style={{padding:11,background:'#eef4ff',borderRadius:9,marginBottom:10,fontWeight:900}}>↻ {msg}<div style={{fontSize:9,marginTop:3}}>No se cerrará hasta confirmar datos reales.</div></div>}{busy==='conape'&&<div style={{padding:11,background:'#fff8e1',borderRadius:9,marginBottom:10,color:'#7a4900'}}>El estado quedó guardado; CONAPE está pendiente.</div>}{error&&<div style={{padding:10,background:'#ffebee',borderRadius:9,marginBottom:10,color:'#b42318'}}>⚠ {error}</div>}<div style={{display:'flex',justifyContent:'flex-end',gap:8}}>{busy==='conape'?<button onClick={()=>fresh(saved||{ok:true})}>Cerrar con datos reales</button>:<><button disabled={!!busy} onClick={onClose}>Cancelar</button><button disabled={!!busy||pregunta&&!choice} onClick={save} style={{background:'#002f6c',color:'#fff'}}>Guardar cambio</button></>}</div></div></div></div>}
function apply(){if(typeof window.ModalEstatus!=='function')return;window.ModalEstatus=Modal;try{ModalEstatus=Modal}catch(_){}window.__AN_STATUS_FRESH_BUILD__=BUILD}window.addEventListener('an:lazy-module-loaded',e=>{if(String(e?.detail?.src||'').includes('admin_students.jsx'))setTimeout(apply,10)});setTimeout(apply,10);
})();
