// F98.4-Z6-CS21A104 · Una ficha por estudiante con movimientos alineados y fecha detectada separada.
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const {LEVEL_ORDER,STATUS_ORDER,clean,normalize,fullDate,shortDate,phone,levelId,levelText,period,disbursementNumber,isAcademicDisbursement01,periodMovementRows,periodFull,openConsult,ReviewTrafficLight,DetailButton,historyRows,movementRowsForLevel,AcademicHistoryLine,WaButton}=N;

function injectGroupedStyles(){
 if(document.getElementById('an-master-conape-grouped-cs21a104'))return;
 const style=document.createElement('style');style.id='an-master-conape-grouped-cs21a104';style.textContent=`
 .master-conape-month-table{min-width:1280px}.master-conape-aligned-cell{padding:0!important}.master-conape-aligned-grid{display:grid;min-width:0}.master-conape-aligned-row{display:grid;grid-template-columns:minmax(370px,36fr) minmax(180px,16fr) minmax(92px,8fr) minmax(118px,8fr);align-items:stretch;border-bottom:1px solid #EEE9DF}.master-conape-aligned-row:last-child{border-bottom:0}.master-conape-aligned-row>div{display:flex;align-items:center;min-width:0;padding:5px 9px;box-sizing:border-box}.master-conape-aligned-row>div+div{border-left:1px solid #F0ECE5}.master-conape-aligned-academic .master-conape-history-item{width:100%;min-height:34px;margin:0}.master-conape-history-alert{gap:4px;flex-wrap:wrap}.master-conape-period-stack,.master-conape-detected-stack,.master-conape-wa-stack{display:grid;gap:5px;width:100%}.master-conape-period-block{min-width:0}.master-conape-period-block .master-conape-period-primary{font-size:10.5px}.master-conape-period-block .master-conape-period-level{margin-top:2px}.master-conape-period-extra{white-space:normal}.master-conape-detected-value{display:block;color:#7A1E2C;font-size:10px;font-weight:950;white-space:nowrap}.master-conape-detected-full{display:block;margin-top:2px;color:#8A93A3;font-size:7.8px;line-height:1.25}.master-conape-wa-stack>*{width:100%;box-sizing:border-box}.master-conape-review-cycles{display:grid;gap:6px;margin-top:7px}.master-conape-review-cycle{padding-top:5px;border-top:1px dashed #D8D1C5}.master-conape-review-cycle:first-child{padding-top:0;border-top:0}.master-conape-review-cycle-tag{display:block;margin-bottom:2px;color:#8B7460;font-size:7.8px;font-weight:900;text-transform:uppercase;letter-spacing:.04em}.master-conape-aligned-empty{color:#C1C7D0;font-size:9px}.master-conape-month-table tr[data-student-group="true"] td{vertical-align:middle}.master-conape-month-table tr[data-student-group="true"] .master-conape-code-cell,.master-conape-month-table tr[data-student-group="true"] .master-conape-student-cell{background:#fff}.master-conape-month-table tr.has-alert[data-student-group="true"] .master-conape-code-cell,.master-conape-month-table tr.has-alert[data-student-group="true"] .master-conape-student-cell{background:#FFF9F5}@media(max-width:900px){.master-conape-aligned-row{grid-template-columns:minmax(340px,36fr) minmax(170px,16fr) minmax(88px,8fr) minmax(110px,8fr)}}`;
 document.head.appendChild(style);
}

function CodeCell({code}){return code?<input className="master-conape-code-input" value={code} readOnly aria-label={`Código ${code}`} title={`Código ${code} · clic para seleccionar`} onFocus={e=>e.currentTarget.select()} onClick={e=>e.currentTarget.select()}/>:<span className="master-conape-code-empty">—</span>}
function studentKey(row,index){const code=clean(row?.code);if(code)return`CODE|${code}`;const cedula=clean(row?.cedula).replace(/\D/g,'');if(cedula)return`CED|${cedula}`;return`ROW|${clean(row?.id)||index}`}

function groupStudentRows(rows){
 const map=new Map();
 (Array.isArray(rows)?rows:[]).forEach((row,index)=>{
  const key=studentKey(row,index);
  if(!map.has(key))map.set(key,{key,base:row,movements:[],historySummary:Array.isArray(row?.historySummary)?row.historySummary:[]});
  const bucket=map.get(key);bucket.movements.push(row);
  if(Number(row?.detectedSort||0)>=Number(bucket.base?.detectedSort||0))bucket.base=row;
  if((row?.historySummary||[]).length>bucket.historySummary.length)bucket.historySummary=row.historySummary;
 });
 return Array.from(map.values()).map(bucket=>{const movementRows=bucket.movements.slice().sort((a,b)=>(LEVEL_ORDER[levelId(a)]||99)-(LEVEL_ORDER[levelId(b)]||99)||(Number(a?.year)||0)-(Number(b?.year)||0)||(Number(a?.month)||0)-(Number(b?.month)||0)||(Number(a?.detectedSort)||0)-(Number(b?.detectedSort)||0));return{...bucket.base,id:`STUDENT|${bucket.key}`,studentGroupKey:bucket.key,movementRows,historySummary:bucket.historySummary}});
}
function studentGroupCount(rows){return groupStudentRows(rows).length}

function StudentCell({group,detail,openDetail,code,reviewSteps,onReview,reviewBusy}){
 const movements=Array.isArray(group?.movementRows)?group.movementRows:[group];
 const eligible=movements.filter(row=>row?.followupEligible!==false&&isAcademicDisbursement01(row));
 const pending=eligible.filter(row=>!row?.appliedInSystem);
 return <div className="master-conape-student-box"><div className="master-conape-student-name" title={group.name||'Sin nombre'}>{group.name||'Sin nombre'}</div><div className="master-conape-student-meta"><span className="master-conape-student-id">{group.cedula||'Sin cédula'}</span><DetailButton row={group} value={detail} onEdit={openDetail}/>{code&&<button className="master-conape-consulta-btn" onClick={()=>openConsult(code)}>Consulta</button>}</div><div className="master-conape-campus-line"><span className={`master-link-status ${group.linked?'linked':'unlinked'}`}>{group.linked?'Vinculado':'Sin vínculo'}</span><span title={group.group||'Sin grupo'}>{group.group||'Sin grupo'}</span></div>{pending.length>1?<div className="master-conape-review-cycles">{pending.map(row=><div key={row.id} className="master-conape-review-cycle"><span className="master-conape-review-cycle-tag">{period(row)}</span><ReviewTrafficLight row={row} step={reviewSteps?.[row.id]??row.reviewStep??0} onChange={onReview} busy={reviewBusy===row.id}/></div>)}</div>:pending.length===1?<ReviewTrafficLight row={pending[0]} step={reviewSteps?.[pending[0].id]??pending[0].reviewStep??0} onChange={onReview} busy={reviewBusy===pending[0].id}/>:eligible.length>0?<ReviewTrafficLight row={eligible[eligible.length-1]} step={0} onChange={onReview} busy={false}/>:null}</div>;
}

function contextLabel(item){const n=Number(item?.number)||0;if(clean(item?.contextLabel))return clean(item.contextLabel);if(n===2)return'Sostenimiento · solo informativo';if(n===3)return'Equipo electrónico · solo informativo';return n>1?`Desembolso ${String(n).padStart(2,'0')} · solo informativo`:'Desembolso académico 01'}
function compactDetected(value){return shortDate(value).replace(/^0/,'').replace('/0','/')}
function PeriodMovementBlock({row}){const context=periodMovementRows(row),primary=context.find(x=>Number(x.number)===1)||context[0],extras=context.filter(x=>x!==primary);return <div className="master-conape-period-block" title={`${periodFull(primary,row)} · Detectado ${fullDate(primary?.detectedAt||row.detectedAt)}`}><span className="master-conape-period-primary">{periodFull(primary,row)}</span>{extras.map((item,index)=><span key={`${item.number||index}-${item.detectedSort||index}`} className="master-conape-period-extra" title="Visible solo como información; no genera seguimiento para la Academia"><b>{periodFull(item,row)}</b> · {contextLabel(item)}</span>)}<span className="master-conape-period-level">{levelText(row)}{row.academicStatus?` · ${row.academicStatus}`:''}</span></div>}
function DetectedMovementBlock({row}){return <div title={fullDate(row?.detectedAt)}><span className="master-conape-detected-value">D-{compactDetected(row?.detectedAt)}</span><span className="master-conape-detected-full">{fullDate(row?.detectedAt)}</span></div>}

function AlignedBody({group,financeMap}){
 const movements=Array.isArray(group?.movementRows)?group.movementRows:[group];
 const levels=historyRows(group?.historySummary,group,movements);
 const code=clean(group?.code);
 return <div className="master-conape-aligned-grid">{levels.map((history,index)=>{const level=clean(history?.level).toUpperCase(),matched=movementRowsForLevel(movements,level);return <div className="master-conape-aligned-row" key={`${history?.sourceRow||index}-${level}`}><div className="master-conape-aligned-academic"><AcademicHistoryLine history={history} movements={matched}/></div><div className="master-conape-aligned-period">{matched.length?<div className="master-conape-period-stack">{matched.map(row=><PeriodMovementBlock key={row.id} row={row}/>)}</div>:<span className="master-conape-aligned-empty">—</span>}</div><div className="master-conape-aligned-detected">{matched.length?<div className="master-conape-detected-stack">{matched.map(row=><DetectedMovementBlock key={row.id} row={row}/>)}</div>:<span className="master-conape-aligned-empty">—</span>}</div><div className="master-conape-aligned-wa">{matched.length?<div className="master-conape-wa-stack">{matched.map(row=>{const finance=financeMap[`${code}|${levelId(row)}`]||financeMap[code]||null;return <WaButton key={row.id} row={row} finance={finance}/>})}</div>:<span className="master-conape-aligned-empty">—</span>}</div></div>})}</div>;
}

function Row({group,index,details,openDetail,financeMap,reviewSteps,onReview,reviewBusy}){const code=clean(group?.code),detail=code&&Object.prototype.hasOwnProperty.call(details,code)?details[code]:clean(group?.detail),movements=Array.isArray(group?.movementRows)?group.movementRows:[group],alert=movements.some(row=>row?.followupEligible!==false&&isAcademicDisbursement01(row)&&!row?.appliedInSystem&&(!row?.linked||row?.mora));return <tr key={group.studentGroupKey||index} className={alert?'has-alert':''} data-student-group="true"><td className="master-conape-code-cell"><CodeCell code={code}/></td><td className="master-conape-student-cell"><StudentCell group={group} detail={detail} openDetail={openDetail} code={code} reviewSteps={reviewSteps} onReview={onReview} reviewBusy={reviewBusy}/></td><td className="master-conape-aligned-cell" colSpan="4"><AlignedBody group={group} financeMap={financeMap}/></td></tr>}

function sortValue(row,key){if(key==='code'){const n=Number(clean(row?.code).replace(/\D/g,''));return Number.isFinite(n)&&n>0?n:clean(row?.code)}if(key==='student')return normalize(row?.name);if(key==='academic')return(LEVEL_ORDER[levelId(row)]||99)*100+(STATUS_ORDER[clean(row?.academicStatus).toUpperCase()]||90);if(key==='period')return(Number(row?.year)||0)*100+(Number(row?.month)||0);if(key==='detected')return Number(row?.detectedSort||0);if(key==='whatsapp')return row?.appliedInSystem?2:(phone(row?.phone)?0:1);return Number(row?.detectedSort||0)}
function compareRows(a,b,sort){const av=sortValue(a,sort.key),bv=sortValue(b,sort.key);let cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'es',{numeric:true,sensitivity:'base'});if(cmp===0)cmp=Number(b?.detectedSort||0)-Number(a?.detectedSort||0);return sort.dir==='asc'?cmp:-cmp}
function SortHeader({id,label,sort,onSort}){const active=sort.key===id;return <button type="button" className="master-conape-sort-btn" data-active={active?'true':'false'} onClick={()=>onSort(id)} title={`Ordenar por ${label}`}><span>{label}</span><span className="master-conape-sort-arrow">{active?(sort.dir==='asc'?'↑':'↓'):'↕'}</span></button>}
function Table({items,details,openDetail,financeMap,empty,sort,onSort,reviewSteps,onReview,reviewBusy}){injectGroupedStyles();const groups=groupStudentRows(items),headers=[['code','Código'],['student','Estudiante'],['academic','Resumen académico'],['period','Periodo / nivel'],['detected','Detectado'],['whatsapp','WhatsApp']];return <div className="master-conape-month-table-wrap"><table className="master-conape-month-table"><colgroup>{[8,24,36,16,8,8].map((w,i)=><col key={i} style={{width:`${w}%`}}/>)}</colgroup><thead><tr>{headers.map(([id,label])=><th key={id}><SortHeader id={id} label={label} sort={sort} onSort={onSort}/></th>)}</tr></thead><tbody>{groups.map((group,index)=><Row key={group.studentGroupKey||index} group={group} index={index} details={details} openDetail={openDetail} financeMap={financeMap} reviewSteps={reviewSteps} onReview={onReview} reviewBusy={reviewBusy}/>)}</tbody></table>{!groups.length&&<div className="master-conape-empty">{empty}</div>}</div>}

function uniqueSorted(values){return Array.from(new Set(values.filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b),'es',{numeric:true,sensitivity:'base'}))}
function dedupeMovementRows(rows){const map=new Map();(rows||[]).forEach(row=>{const key=[clean(row?.cedula||row?.code).replace(/\D/g,''),Number(row?.year)||0,Number(row?.month)||0,disbursementNumber(row)||1].join('|'),current=map.get(key);if(!current||Number(row?.detectedSort||0)>=Number(current?.detectedSort||0)){const merged={...current,...row},context=[...(current?.periodMovements||[]),...(row?.periodMovements||[])];merged.periodMovements=Array.from(new Map(context.map(item=>[[item.number,item.month,item.year].join('|'),item])).values());map.set(key,merged)}});return Array.from(map.values())}
function filterRows(rows,f){return rows.filter(row=>N.matchesSearch(row,f.query)&&(f.level==='ALL'||(f.level==='SIN_NIVEL'?!levelId(row):levelId(row)===f.level))&&(f.status==='ALL'||clean(row?.academicStatus||'SIN_ESTADO').toUpperCase()===f.status)&&(f.period==='ALL'||`${String(row?.month||0).padStart(2,'0')}/${row?.year||0}`===f.period)&&(f.whatsapp==='ALL'||(f.whatsapp==='AVAILABLE'&&phone(row?.phone)&&!row?.appliedInSystem)||(f.whatsapp==='MISSING'&&!phone(row?.phone))||(f.whatsapp==='CLOSED'&&row?.appliedInSystem)))}
Object.assign(N,{CodeCell,studentKey,groupStudentRows,studentGroupCount,StudentCell,contextLabel,compactDetected,PeriodMovementBlock,DetectedMovementBlock,AlignedBody,Row,sortValue,compareRows,SortHeader,Table,uniqueSorted,dedupeMovementRows,filterRows});
})();
