// F98.4-Z6-CS21A101 · Tabla: 01 gestionable; 02/03 solo informativos
(function(){
'use strict';
const N=window.ANMasterConape96;if(!N)throw Error('CS21A96 core no cargado');
const {LEVEL_ORDER,STATUS_ORDER,clean,normalize,fullDate,shortDate,phone,levelId,levelText,disbursementNumber,isAcademicDisbursement01,reviewStepValue,periodMovementRows,periodFull,openConsult,ReviewTrafficLight,DetailButton,AcademicHistory,WaButton}=N;
function CodeCell({code}){return code?<input className="master-conape-code-input" value={code} readOnly aria-label={`Código ${code}`} title={`Código ${code} · clic para seleccionar`} onFocus={e=>e.currentTarget.select()} onClick={e=>e.currentTarget.select()}/>:<span className="master-conape-code-empty">—</span>}
function StudentCell({row,detail,openDetail,code,reviewStep,onReview,reviewBusy}){const eligible=row?.followupEligible!==false&&isAcademicDisbursement01(row);return <div className="master-conape-student-box"><div className="master-conape-student-name" title={row.name||'Sin nombre'}>{row.name||'Sin nombre'}</div><div className="master-conape-student-meta"><span className="master-conape-student-id">{row.cedula||'Sin cédula'}</span><DetailButton row={row} value={detail} onEdit={openDetail}/>{code&&<button className="master-conape-consulta-btn" onClick={()=>openConsult(code)}>Consulta</button>}</div><div className="master-conape-campus-line"><span className={`master-link-status ${row.linked?'linked':'unlinked'}`}>{row.linked?'Vinculado':'Sin vínculo'}</span><span title={row.group||'Sin grupo'}>{row.group||'Sin grupo'}</span></div>{eligible&&<ReviewTrafficLight row={row} step={reviewStep} onChange={onReview} busy={reviewBusy}/>}</div>}
function contextLabel(item){const n=Number(item?.number)||0;if(clean(item?.contextLabel))return clean(item.contextLabel);if(n===2)return'Sostenimiento · solo informativo';if(n===3)return'Equipo electrónico · solo informativo';return n>1?`Desembolso ${String(n).padStart(2,'0')} · solo informativo`:'Desembolso académico 01'}
function PeriodCell({row}){const context=periodMovementRows(row),primary=context.find(x=>Number(x.number)===1)||context[0],extras=context.filter(x=>x!==primary);return <div className="master-conape-period-box" title={`${periodFull(primary,row)} · Detectado ${fullDate(primary?.detectedAt||row.detectedAt)}`}><span className="master-conape-period-primary">{periodFull(primary,row)} <em>- D-{shortDate(primary?.detectedAt||row.detectedAt)}</em></span>{extras.map((item,index)=><span key={`${item.number||index}-${item.detectedSort||index}`} className="master-conape-period-extra" title="Visible solo como información; no genera seguimiento para la Academia"><b>{periodFull(item,row)}</b> · {contextLabel(item)} · D-{shortDate(item.detectedAt)}</span>)}<span className="master-conape-period-level">{levelText(row)}{row.academicStatus?` · ${row.academicStatus}`:''}</span></div>}
function Row({row,index,details,openDetail,financeMap,reviewSteps,onReview,reviewBusy}){const code=clean(row?.code),detail=code&&Object.prototype.hasOwnProperty.call(details,code)?details[code]:clean(row.detail),finance=financeMap[`${code}|${levelId(row)}`]||financeMap[code]||null,cell={verticalAlign:'middle',minWidth:0},eligible=row?.followupEligible!==false&&isAcademicDisbursement01(row);return <tr key={row.id||index} className={eligible&&!row.appliedInSystem&&(!row.linked||row.mora)?'has-alert':''} data-applied={row.appliedInSystem?'true':'false'} data-followup={eligible?'academic-01':'informative'}><td className="master-conape-code-cell" style={cell}><CodeCell code={code}/></td><td className="master-conape-student-cell" style={cell}><StudentCell row={row} detail={detail} openDetail={openDetail} code={code} reviewStep={reviewSteps?.[row.id]??row.reviewStep??0} onReview={onReview} reviewBusy={reviewBusy===row.id}/></td><td className="master-conape-history-cell" style={cell}><AcademicHistory items={row.historySummary} row={row}/></td><td className="master-conape-period-cell" style={cell}><PeriodCell row={row}/></td><td className="master-conape-wa-cell" style={cell}><WaButton row={row} finance={finance}/></td></tr>}
function sortValue(row,key){if(key==='code'){const n=Number(clean(row?.code).replace(/\D/g,''));return Number.isFinite(n)&&n>0?n:clean(row?.code)}if(key==='student')return normalize(row?.name);if(key==='academic')return(LEVEL_ORDER[levelId(row)]||99)*100+(STATUS_ORDER[clean(row?.academicStatus).toUpperCase()]||90);if(key==='period')return(Number(row?.year)||0)*100+(Number(row?.month)||0);if(key==='whatsapp')return row?.appliedInSystem?2:(phone(row?.phone)?0:1);return Number(row?.detectedSort||0)}
function compareRows(a,b,sort){const av=sortValue(a,sort.key),bv=sortValue(b,sort.key);let cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv),'es',{numeric:true,sensitivity:'base'});if(cmp===0)cmp=Number(b?.detectedSort||0)-Number(a?.detectedSort||0);return sort.dir==='asc'?cmp:-cmp}
function SortHeader({id,label,sort,onSort}){const active=sort.key===id;return <button type="button" className="master-conape-sort-btn" data-active={active?'true':'false'} onClick={()=>onSort(id)} title={`Ordenar por ${label}`}><span>{label}</span><span className="master-conape-sort-arrow">{active?(sort.dir==='asc'?'↑':'↓'):'↕'}</span></button>}
function Table({items,details,openDetail,financeMap,empty,sort,onSort,reviewSteps,onReview,reviewBusy}){const headers=[['code','Código'],['student','Estudiante'],['academic','Resumen académico'],['period','Periodo / nivel'],['whatsapp','WhatsApp']];return <div className="master-conape-month-table-wrap"><table className="master-conape-month-table"><colgroup>{[8,24,39,15,14].map((w,i)=><col key={i} style={{width:`${w}%`}}/>)}</colgroup><thead><tr>{headers.map(([id,label])=><th key={id}><SortHeader id={id} label={label} sort={sort} onSort={onSort}/></th>)}</tr></thead><tbody>{items.map((r,i)=><Row key={r.id||i} row={r} index={i} details={details} openDetail={openDetail} financeMap={financeMap} reviewSteps={reviewSteps} onReview={onReview} reviewBusy={reviewBusy}/>)}</tbody></table>{!items.length&&<div className="master-conape-empty">{empty}</div>}</div>}
function uniqueSorted(values){return Array.from(new Set(values.filter(Boolean))).sort((a,b)=>String(a).localeCompare(String(b),'es',{numeric:true,sensitivity:'base'}))}
function dedupeMovementRows(rows){const map=new Map();(rows||[]).forEach(row=>{const key=[clean(row?.cedula||row?.code).replace(/\D/g,''),Number(row?.year)||0,Number(row?.month)||0,disbursementNumber(row)||1].join('|'),current=map.get(key);if(!current||Number(row?.detectedSort||0)>=Number(current?.detectedSort||0)){const merged={...current,...row},context=[...(current?.periodMovements||[]),...(row?.periodMovements||[])];merged.periodMovements=Array.from(new Map(context.map(item=>[[item.number,item.month,item.year].join('|'),item])).values());map.set(key,merged)}});return Array.from(map.values())}
function filterRows(rows,f){return rows.filter(row=>N.matchesSearch(row,f.query)&&(f.level==='ALL'||(f.level==='SIN_NIVEL'?!levelId(row):levelId(row)===f.level))&&(f.status==='ALL'||clean(row?.academicStatus||'SIN_ESTADO').toUpperCase()===f.status)&&(f.period==='ALL'||`${String(row?.month||0).padStart(2,'0')}/${row?.year||0}`===f.period)&&(f.whatsapp==='ALL'||(f.whatsapp==='AVAILABLE'&&phone(row?.phone)&&!row?.appliedInSystem)||(f.whatsapp==='MISSING'&&!phone(row?.phone))||(f.whatsapp==='CLOSED'&&row?.appliedInSystem)))}
Object.assign(N,{CodeCell,StudentCell,contextLabel,PeriodCell,Row,sortValue,compareRows,SortHeader,Table,uniqueSorted,dedupeMovementRows,filterRows});
})();
