// F98.4-Z6-CS21A99 · Estado y operaciones del asistente.
(function(){'use strict';const N=window.ANQuickUpdate99,{NEXT,clean,upper,num,round,money,requestId,post,fillDebt}=N;
function useQuickUpdate(props){const estudiante=props.estudiante||{},actual=upper(estudiante.estatus||'CA'),codigo=clean(estudiante.codigo||estudiante.rec_m),grupo=clean(estudiante.grupo||estudiante.GRUPO),nivel=upper(props.nivel),siguiente=NEXT[nivel]||'';
 const[nuevo,setNuevo]=React.useState(actual),[step,setStep]=React.useState('ACADEMIC'),[busy,setBusy]=React.useState(''),[error,setError]=React.useState(''),[academic,setAcademic]=React.useState(null),[model,setModel]=React.useState(null),[query,setQuery]=React.useState(''),[receipt,setReceipt]=React.useState(null),[selected,setSelected]=React.useState({}),[payment,setPayment]=React.useState(null),[conape,setConape]=React.useState(null);
 const academicReq=React.useRef(requestId('ACAD-CS21A99')),paymentReq=React.useRef(requestId('PAY-CS21A99')),items=model?.items||[],total=round(items.reduce((a,x)=>a+num(selected[x.tipo]),0)),available=num(receipt?.saldo),after=round(Math.max(0,available-total)),promo=actual==='CA'&&nuevo==='APR';
 function amount(type,value){setSelected(s=>({...s,[type]:round(value)}));setError('')}
 function complete(rec=receipt){if(!rec)return setError('Primero seleccioná un comprobante.');setSelected(fillDebt(items,rec));setError('')}
 async function legacy(){if(nuevo===actual)return props.onClose?.();setBusy('legacy');setError('');try{const r=await post('actualizarEstatus',{codigo,cod_estudiante:codigo,nivel,estatus:nuevo,nota:estudiante.nota??null,grupo});props.onSuccess?.(r);props.onClose?.()}catch(e){setError(e.message||String(e))}finally{setBusy('')}}
 async function academicSave(){setBusy('academic');setError('');try{const r=await post('aplicarPuestaAlDiaAcademica',{request_id:academicReq.current,codigo,cod_estudiante:codigo,nivel,nota:estudiante.nota??null,grupo},120000);setAcademic(r);setModel(r.pago||null);setSelected({});setStep(r.pago?.sin_deuda||!r.pago?.items?.some(x=>x.seleccionable)?'CONAPE':'PAYMENT')}catch(e){setError(e.message||String(e))}finally{setBusy('')}}
 async function receiptFind(){const doc=clean(query);if(!/^\d{4,}$/.test(doc))return setError('Pegá el número exacto del comprobante bancario.');setBusy('receipt');setError('');try{const r=await post('getComprobantes',{numero_documento:doc,consulta_en:Date.now()},50000),found=(r.comprobantes||[]).find(x=>clean(x.doc)===doc);if(!found)throw Error(`El comprobante ${doc} no existe o ya no tiene saldo disponible.`);setReceipt(found);setSelected(fillDebt(items,found))}catch(e){setReceipt(null);setSelected({});setError(e.message||String(e))}finally{setBusy('')}}
 async function paymentApply(){if(!receipt)return setError('Seleccioná el comprobante.');if(total<=.009)return setError('Agregá al menos un rubro con saldo pendiente.');if(total>available+.01)return setError(`El total ${money(total)} supera el saldo disponible ${money(available)}.`);const rubros=items.filter(x=>num(selected[x.tipo])>.009).map(x=>({tipo:x.tipo,nivel:model.nivel,monto:round(selected[x.tipo]),grupo:model.grupo}));setBusy('payment');setError('');try{const r=await post('aplicarPagoPuestaAlDia',{request_id:paymentReq.current,codigo,doc:receipt.doc,monto_total:total,rubros},120000);setPayment(r);setStep('CONAPE')}catch(e){setError(e.message||String(e))}finally{setBusy('')}}
 async function conapeSync(){setBusy('conape');setError('');try{const r=await post('sincronizarConapePuestaAlDia',{codigo,operacion_id:payment?.operacion_id||''},120000);setConape(r);setStep('DONE');props.onSuccess?.({ok:true,codigo,academic,payment,conape:r,quick_update:true})}catch(e){setError(e.message||String(e))}finally{setBusy('')}}
 function conapePending(){setConape({ok:false,pendiente:true,mensaje:'CONAPE quedó pendiente por decisión del operador.'});setStep('DONE');props.onSuccess?.({ok:true,codigo,academic,payment,conape_pending:true,quick_update:true})}
 function finish(){props.onClose?.();window.dispatchEvent(new CustomEvent('an:quick-update-finished',{detail:{codigo,academic,payment,conape}}))}
 return{...props,estudiante,actual,codigo,grupo,nivel,siguiente,nuevo,setNuevo,step,busy,error,academic,model,query,setQuery,receipt,selected,payment,conape,items,total,available,after,promo,amount,complete,legacy,academicSave,receiptFind,paymentApply,conapeSync,conapePending,finish};}
N.useQuickUpdate=useQuickUpdate;})();
