// CS21A77 · Asistencia docente · panel superior
(function(){
const A=window.ANAtt77,C=A.C;
function AttendanceTop77({v}){const {d,items,lessons,avg,grades,gavg,closed,setSel}=v;return <>
<header style={{display:'flex',justifyContent:'space-between',gap:14,alignItems:'end',flexWrap:'wrap',marginBottom:16}}><div><div style={{fontSize:10,fontWeight:950,letterSpacing:'.14em',color:C.wine}}>GESTIÓN ACADÉMICA</div><h1 style={{fontFamily:'var(--f-serif)',fontSize:38,fontWeight:500,color:C.ink,margin:'5px 0'}}>Centro de <em>seguimiento</em></h1><div style={{fontSize:12,color:'var(--ink-3)'}}>Asistencia, notas y comentarios en una lectura amplia. Las acciones siguen en Mis grupos.</div></div><select value={d.codGrupo||''} onChange={e=>d.cambiarGrupo(e.target.value)} style={{minWidth:270,height:42,border:'1.5px solid #AEBCCD',borderRadius:10,padding:'0 11px',fontWeight:800}}>{(d.grupos||[]).map(g=><option key={A.code(g)} value={A.code(g)}>{A.code(g)} · {A.level(g.nivel||g.nivelId)}</option>)}</select></header>
<div style={{background:`linear-gradient(135deg,${C.ink},${C.navy})`,color:'#fff',borderRadius:14,padding:'13px 15px',marginBottom:13,display:'flex',justifyContent:'space-between',gap:10,flexWrap:'wrap'}}><div><b>{d.codGrupo}</b><div style={{fontSize:10,opacity:.8,marginTop:3}}>{A.level(d.nivel)} · {d.nombre}</div></div><span>{closed} cerradas · {lessons.length} programadas</span></div>
<div className="a77k"><A.Metric label="Estudiantes" value={items.length} sub="Roster activo del grupo" color={C.navy}/><A.Metric label="Asistencia promedio" value={avg?avg+'%':'—'} sub="Referencia grupal" color={A.tone(avg||null)}/><A.Metric label="Nota promedio" value={gavg||'—'} sub={`${grades.length} con componentes`} color={gavg?A.tone(gavg):'#98A2B3'}/><A.Metric label="Avance" value={lessons.length?Math.round(closed/lessons.length*100)+'%':'—'} sub={`${closed} de ${lessons.length} actividades`} color={C.purple}/></div>
<div className="a77charts" style={{marginTop:14}}><section className="card" style={{padding:16,display:'flex',gap:18,alignItems:'center'}}><A.Donut value={avg}/><div style={{flex:1}}><h3 style={{margin:'0 0 12px',color:C.ink}}>Panorama del grupo</h3><A.Bars items={items}/></div></section><section className="card" style={{padding:16}}><h3 style={{margin:0,color:C.ink}}>Lectura de seguimiento</h3><p style={{fontSize:11,color:'var(--ink-3)'}}>Rojo señala asistencia o nota menor a 70; naranja indica revisión. No modifica estados.</p><div style={{display:'flex',gap:8,flexWrap:'wrap'}}>{items.slice().sort((a,b)=>(a.sig.c===C.red?-1:1)).slice(0,8).map(x=><button key={x.s.code} onClick={()=>setSel(x.s.code)} style={{border:`1px solid ${x.sig.c}`,background:x.sig.b,color:x.sig.c,borderRadius:999,padding:'6px 9px',fontSize:9,fontWeight:900,cursor:'pointer'}}>{x.s.name.split(' ')[0]} · {x.p==null?'—':x.p+'%'}</button>)}</div></section></div>
</>}
A.AttendanceTop77=AttendanceTop77;
})();
