// CS21A77 · Asistencia docente · widgets
(function(){
const A=window.ANAtt77,C=A.C;
function Donut({value}){const v=Math.max(0,Math.min(100,Number(value)||0)),r=38,d=2*Math.PI*r;return <div style={{width:104,height:104,position:'relative',display:'grid',placeItems:'center'}}><svg width="104" height="104" style={{transform:'rotate(-90deg)'}}><circle cx="52" cy="52" r={r} fill="none" stroke="#E8EDF3" strokeWidth="10"/><circle cx="52" cy="52" r={r} fill="none" stroke={A.tone(v)} strokeWidth="10" strokeLinecap="round" strokeDasharray={`${d*v/100} ${d-d*v/100}`}/></svg><strong style={{position:'absolute',fontSize:22,color:A.tone(v)}}>{v}%</strong></div>}
function Bars({items}){const bands=[['85–100%',C.green,x=>x>=85],['70–84%',C.amber,x=>x>=70&&x<85],['Menos de 70%',C.red,x=>x<70],['Sin dato','#98A2B3',x=>x==null]];return <div style={{display:'grid',gap:10}}>{bands.map(([l,c,f])=>{const n=items.filter(x=>f(x.p)).length,w=items.length?n/items.length*100:0;return <div key={l}><div style={{display:'flex',justifyContent:'space-between',fontSize:10,fontWeight:800}}><span>{l}</span><span style={{color:c}}>{n}</span></div><div style={{height:9,background:'#EEF1F5',borderRadius:9,marginTop:4}}><div style={{width:w+'%',height:'100%',background:c,borderRadius:9}}/></div></div>})}</div>}
function Metric({label,value,sub,color}){return <article className="card" style={{padding:15,borderTop:`4px solid ${color}`}}><div style={{fontSize:9,fontWeight:900,letterSpacing:'.12em',color:'var(--ink-3)',textTransform:'uppercase'}}>{label}</div><div style={{fontSize:29,fontWeight:950,color,marginTop:7}}>{value}</div><div style={{fontSize:10,color:'var(--ink-3)',marginTop:5}}>{sub}</div></article>}
function StudentList({items,selected,onSelect,query,setQuery}){return <section className="card" style={{padding:0,overflow:'hidden'}}><div style={{padding:15,borderBottom:`1px solid ${C.line}`}}><strong style={{fontSize:17,color:C.ink}}>Estudiantes</strong><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar nombre, código o cédula" style={{width:'100%',height:39,marginTop:10,border:'1.5px solid #B7C3D4',borderRadius:10,padding:'0 11px',boxSizing:'border-box'}}/></div><div style={{maxHeight:620,overflowY:'auto'}}>{items.map(x=><button key={x.s.code} onClick={()=>onSelect(x.s.code)} style={{width:'100%',border:0,borderBottom:`1px solid ${C.line}`,background:selected===x.s.code?'#EAF2FB':'#FFF',padding:'11px 13px',textAlign:'left',cursor:'pointer',boxShadow:selected===x.s.code?`inset 4px 0 ${C.navy}`:'none'}}><div style={{display:'flex',justifyContent:'space-between',gap:8}}><strong style={{fontSize:12,color:C.ink}}>{x.s.name}</strong><span style={{width:9,height:9,borderRadius:'50%',background:x.sig.c,boxShadow:`0 0 0 3px ${x.sig.b}`}}/></div><div style={{fontSize:9,color:'var(--ink-3)',marginTop:3}}>Código {x.s.code}</div><div style={{display:'flex',gap:5,marginTop:6,flexWrap:'wrap'}}><small>Asistencia {x.p==null?'—':x.p+'%'}</small><small>Nota {x.g==null?'—':x.g}</small>{x.comments>0&&<small>💬 {x.comments}</small>}</div></button>)}</div></section>}
Object.assign(A,{Donut,Bars,Metric,StudentList});
})();
