// F98.4-Z6-CS21A129 · Contenido académico acumulativo y planeamiento PDF por lección.
/* global React, ReactDOM */
(function(){
  'use strict';
  const VERSION='F98.4-Z6-CS21A129';
  const LEVELS=['B1','B2','I1','I2'];
  const NAMES={B1:'Básico I',B2:'Básico II',I1:'Intermedio I',I2:'Intermedio II'};
  const BOOKS={B1:'Interchange Intro',B2:'Interchange 1',I1:'Interchange 2',I2:'Interchange 3'};
  const PLAN_DOCS={B1:'1yTq26DzSwAwajHqH_I8RfN2Z-DHoM_Jl',B2:'1DbJ2-1SGEjxCMccQA2l8YuANehWm8qC9',I1:'1110cof4beNl_ME7HMOgDmHCx0N_Ux-kc',I2:'1CajioftRWZyrDXX5XmKOswIIYNB_A7ln'};
  const ROUTES=new Set(['planeamiento_estudiante','libros_audios_estudiante','recursos_adicionales','plan_estudio_estudiante']);
  const ACCESS_CACHE=window.__AN_CONTENT_ACCESS_CS21A125__||(window.__AN_CONTENT_ACCESS_CS21A125__={value:null,promise:null});
  let root=null,currentRoute='';

  const clean=v=>String(v==null?'':v).replace(/\s+/g,' ').trim();
  function contentAccessSafeUserError(raw,fallback,context=''){const msg=clean(raw);if(msg)console.warn('[StudentContentAccess] Detalle técnico oculto al estudiante.',{context,error:msg});const tecnico=/apps?\s*script|backend|endpoint|stack|exception|trace|<html|json|token|sesion_requerida|unauthorized|forbidden|internal server|status\s*\d{3}|http\s*\d{3}|getAccesoContenidoEstudiante|getBibliotecaNivelEstudiante|getAudioPistaEstudiante|base64|mime|drive\.google\.com|failed to fetch|networkerror|typeerror|referenceerror|syntaxerror|cannot read|[A-Za-z0-9_-]{30,}/i;return !msg||tecnico.test(msg)?fallback:msg;}
  const pad=n=>String(n).padStart(2,'0');
  const previewUrl=id=>`https://drive.google.com/file/d/${id}/preview`;
  const downloadUrl=id=>`https://drive.google.com/uc?export=download&id=${id}`;
  function session(){try{return (typeof window.getSesion==='function'?window.getSesion():JSON.parse(sessionStorage.getItem('an_usuario')||'null'))||{};}catch(_){return{};}}
  function token(){return typeof window.getSessionToken==='function'?window.getSessionToken():'';}
  async function post(fn,payload={}){const r=await fetch(`${window.APPS_SCRIPT_URL}?fn=${encodeURIComponent(fn)}`,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({fn,token:token(),...payload})});const raw=await r.text();let data;try{data=raw?JSON.parse(raw):null;}catch(_){throw new Error('El servidor devolvió una respuesta inválida.');}if(!r.ok||!data?.ok)throw new Error(data?.mensaje||data?.motivo||data?.error||`HTTP ${r.status}`);return data;}
  function sessionFallback(){const u=session(),s=u.niveles_estatus||u.NIVELES_ESTATUS||{},allowed=[],states={};LEVELS.forEach((n,i)=>{const st=clean(s[n]).toUpperCase();states[n]=st;if(['CA','APR','CNV'].includes(st))allowed.splice(0,allowed.length,...LEVELS.slice(0,i+1));});const code=clean(u.codigo||u.CODIGO).toUpperCase(),group=clean(u.grupo||u.grupoActivo);if(!allowed.length&&/^AN0626-/.test(code))allowed.push('B1','B2','I1');if(!allowed.length&&/^AN0726-/.test(code))allowed.push('B1');return{ok:true,acceso:allowed.length>0,niveles_autorizados:allowed,nivel_maximo:allowed[allowed.length-1]||'',estados:states,demo:/^AN(?:0626|0726)-/.test(code),fallback:true,grupo:group};}
  function loadAccess(force=false){if(force){ACCESS_CACHE.value=null;ACCESS_CACHE.promise=null;}if(ACCESS_CACHE.value)return Promise.resolve(ACCESS_CACHE.value);if(ACCESS_CACHE.promise)return ACCESS_CACHE.promise;const u=session(),codigo=clean(u.codigo||u.CODIGO||u.cedula||u.CEDULA);ACCESS_CACHE.promise=post('getAccesoContenidoEstudiante',{codigo}).then(data=>{ACCESS_CACHE.value=data;return data;}).catch(err=>{const fallback=sessionFallback();console.warn('[StudentContentAccess] Detalle técnico oculto al estudiante.',{context:'get_acceso_contenido',error:err?.message||String(err)});ACCESS_CACHE.value=fallback;return fallback;}).finally(()=>{ACCESS_CACHE.promise=null;});return ACCESS_CACHE.promise;}
  function ensureCss(){if(document.getElementById('an-content-access-cs21a125-css'))return;const l=document.createElement('link');l.id='an-content-access-cs21a125-css';l.rel='stylesheet';l.href='styles/student_content_access_cs21a125.css?v=F98.4Z6CS21A126';document.head.appendChild(l);}
  function host(){let h=document.getElementById('an-content-access-host-cs21a125');if(h)return h;const app=document.querySelector('.app');if(!app)return null;h=document.createElement('main');h.id='an-content-access-host-cs21a125';h.className='main an-content-access-host-cs21a125';const m=app.querySelector(':scope > .main');if(m)m.insertAdjacentElement('afterend',h);else app.appendChild(h);return h;}
  function markActive(route){const sb=document.querySelector('.student-sb');if(!sb)return;sb.querySelectorAll('.sb-item.active').forEach(x=>x.classList.remove('active'));sb.querySelector(`[data-nav-id="${route}"]`)?.classList.add('active');}
  function close(keepHistory=true){document.body.classList.remove('an-content-access-open');if(root){try{root.unmount();}catch(_){}root=null;}document.getElementById('an-content-access-host-cs21a125')?.remove();currentRoute='';if(!keepHistory&&ROUTES.has(location.hash.replace(/^#/,'')))history.replaceState({},'','#dashboard');}
  function open(route,push=true){if(!ROUTES.has(route))return;ensureCss();try{window.CS21A120_STUDENT_MENU?.close?.();}catch(_){}const h=host();if(!h)return;currentRoute=route;document.body.classList.add('an-content-access-open');document.body.classList.remove('an-mobile-nav-open');markActive(route);if(!root)root=ReactDOM.createRoot(h);root.render(<ContentAccessRoute route={route}/>);if(push&&location.hash!==`#${route}`)history.pushState({cs21a125:true},'',`#${route}`);window.scrollTo(0,0);}

  function State({children,error,onRetry}){return <div className={'ca125-state '+(error?'error':'')}><strong>{children}</strong>{onRetry&&<button className="btn btn-primary" onClick={onRetry}>Reintentar</button>}</div>;}
  function Header({title,desc,access,level,setLevel}){return <><div className="ca125-header"><div><span>Contenido académico autorizado</span><h1>{title}</h1><p>{desc}</p></div><div className="ca125-rule">Hasta {access.nivel_maximo?`${access.nivel_maximo} · ${NAMES[access.nivel_maximo]}`:'sin nivel habilitado'}</div></div><div className="ca125-levels">{access.niveles_autorizados.map(n=><button key={n} className={level===n?'active':''} onClick={()=>setLevel(n)}><b>{n}</b><span>{NAMES[n]}</span><small>{access.estados?.[n]||'Nivel anterior autorizado'}</small></button>)}</div></>;}
  function useAccess(){const[state,setState]=React.useState({loading:true,error:'',access:null});const load=React.useCallback((force=false)=>{setState({loading:true,error:'',access:null});loadAccess(force).then(access=>setState({loading:false,error:access.acceso?'':(access.diagnostico||'No hay niveles académicos habilitados.'),access})).catch(e=>setState({loading:false,error:contentAccessSafeUserError(e?.message||String(e),'No pudimos verificar tus niveles autorizados. Intentá nuevamente.','get_acceso_contenido'),access:null}));},[]);React.useEffect(()=>load(false),[load]);return{...state,reload:()=>load(true)};}
  function useCatalog(level){const u=session(),codigo=clean(u.codigo||u.CODIGO||u.cedula||u.CEDULA),group=clean(u.grupoActivo||u.grupo||u.grupos?.[0]);const[state,setState]=React.useState({loading:true,error:'',catalog:null});const load=React.useCallback(()=>{if(!level)return;setState({loading:true,error:'',catalog:null});post('getBibliotecaNivelEstudiante',{nivel:level,codigo,cod_grupo:group,vista:'estudiante'}).then(r=>{if(r.acceso===false)throw new Error(r.motivo||'Contenido no habilitado.');if(!r.catalogo)throw new Error('El catálogo del nivel no respondió.');setState({loading:false,error:'',catalog:r.catalogo});}).catch(e=>setState({loading:false,error:contentAccessSafeUserError(e?.message||String(e),'No pudimos cargar el contenido de este nivel. Intentá de nuevo.','get_biblioteca_nivel'),catalog:null}));},[level,codigo,group]);React.useEffect(load,[load]);return{...state,reload:load,codigo,group};}
  function ContentAccessRoute({route}){const a=useAccess();const[level,setLevel]=React.useState('');React.useEffect(()=>{if(a.access?.nivel_maximo&&!level)setLevel(a.access.nivel_maximo);},[a.access,level]);if(a.loading)return <State>Cargando niveles autorizados…</State>;if(a.error||!a.access?.acceso)return <State error onRetry={a.reload}>{a.error||'Sin acceso académico.'}</State>;if(route==='plan_estudio_estudiante')return <PlanView access={a.access} level={level} setLevel={setLevel}/>;if(route==='planeamiento_estudiante')return <PlaneamientoView access={a.access} level={level} setLevel={setLevel}/>;if(route==='libros_audios_estudiante')return <BooksView access={a.access} level={level} setLevel={setLevel}/>;return <ResourcesView access={a.access} level={level} setLevel={setLevel}/>;}
  function PlanView({access,level,setLevel}){const id=PLAN_DOCS[level];return <section className="ca125-page"><Header title="Plan de Estudio" desc="Consulta el plan del nivel actual y de todos los niveles anteriores autorizados." {...{access,level,setLevel}}/><div className="ca125-doc"><div><strong>{NAMES[level]}</strong><span>{BOOKS[level]}</span><button className="btn btn-primary" onClick={()=>window.open(downloadUrl(id),'_blank','noopener,noreferrer')}>Descargar</button></div><iframe title={`Plan ${level}`} src={previewUrl(id)}/></div></section>;}
  function PlaneamientoView({access,level,setLevel}){
    const[lesson,setLesson]=React.useState(1);
    React.useEffect(()=>setLesson(1),[level]);
    const ids=window.__AN_STUDENT_PLANEAMIENTO_PDFS_CS21A129__?.[level]||[];
    const id=ids[lesson-1]||'';
    const title=`Lección ${pad(lesson)} · ${NAMES[level]||level}`;
    return <section className="ca125-page" data-planeamiento-level={level}>
      <Header title="Planeamiento por lección" desc="Consulta el PDF oficial de cada lección del nivel actual y de todos los niveles anteriores autorizados." {...{access,level,setLevel}}/>
      <div className="ca129-planeamiento">
        <div className="ca129-planeamiento-head">
          <div><h2>Planeamiento · {NAMES[level]}</h2><p>Seleccioná una lección para verla directamente desde Drive.</p></div>
          <span className="ca129-planeamiento-count">{ids.length} de 32 PDFs</span>
        </div>
        {ids.length===32?<div className="ca129-lesson-grid" data-lesson-count={ids.length}>{ids.map((fileId,index)=>{const number=index+1;return <button key={fileId} type="button" className={'ca129-lesson-btn '+(lesson===number?'active':'')} aria-pressed={lesson===number} aria-label={`Mostrar lección ${pad(number)}`} onClick={()=>setLesson(number)}><span>Lección</span><strong>{pad(number)}</strong></button>;})}</div>:<div className="ca129-planeamiento-missing">No se encontró el catálogo completo de 32 lecciones para este nivel.</div>}
        {id&&<div className="ca129-pdf-view">
          <div className="ca129-pdf-head">
            <div className="ca129-pdf-title"><small>PDF seleccionado</small><strong>{title}</strong><span>Planeamiento estudiantil oficial del nivel {level}.</span></div>
            <div className="ca129-pdf-actions">
              <a className="btn" href={previewUrl(id)} target="_blank" rel="noopener noreferrer">Abrir PDF</a>
              <a className="btn btn-primary" href={downloadUrl(id)} target="_blank" rel="noopener noreferrer">Descargar PDF</a>
            </div>
          </div>
          <iframe key={`${level}-${lesson}`} title={title} src={previewUrl(id)} allow="autoplay"/>
        </div>}
      </div>
    </section>;
  }
  function BooksView({access,level,setLevel}){const d=useCatalog(level),[unit,setUnit]=React.useState(''),[track,setTrack]=React.useState(null);React.useEffect(()=>{setUnit('');setTrack(null);},[level]);if(d.loading)return <State>Cargando libros y audios…</State>;if(d.error)return <State error onRetry={d.reload}>{d.error}</State>;const Proxy=window.StudentBooksProxyCS21A126,units=d.catalog?.audios_unidades||[],u=units.find((x,i)=>String(x.key??i)===unit),total=units.reduce((sum,x)=>sum+((x?.pistas||[]).length),0);return <section className="ca125-page"><Header title="Libros y Audios" desc="Visor visual de libros y audios del nivel actual y de todos los niveles anteriores autorizados." {...{access,level,setLevel}}/>{typeof Proxy==='function'?<Proxy key={level} level={level}/>:<State error>El visor visual de libros no está disponible.</State>}<div className="ca125-card"><div className="ca125-card-head"><div><h2>Audios de {NAMES[level]}</h2><p>Seleccioná una unidad y reproducí las pistas oficiales del nivel.</p></div><div className="ca125-mini-stats"><span>{units.length} unidad(es)</span><span>{total} pista(s)</span></div></div><label>Unidad</label><select value={unit} onChange={e=>{setUnit(e.target.value);setTrack(null);}}><option value="">Seleccioná una unidad</option>{units.map((x,i)=><option key={x.key??i} value={String(x.key??i)}>{x.label||`Unidad ${i+1}`}</option>)}</select>{u&&<div className="ca125-tracks">{(u.pistas||[]).map(x=><div key={x.id}><button onClick={()=>setTrack(track?.id===x.id?null:x)}><span>▶</span><strong>{x.nombre}</strong><small>{u.label||'Audio de unidad'}</small></button>{track?.id===x.id&&<Audio track={x} level={level} codigo={d.codigo} group={d.group}/>}</div>)}</div>}{!u&&<div className="ca125-empty">Elegí una unidad para mostrar sus audios.</div>}</div></section>;}
  function Audio({track,level,codigo,group}){const[state,setState]=React.useState({loading:true,error:'',src:''});React.useEffect(()=>{let live=true,url='';post('getAudioPistaEstudiante',{nivel,codigo,cod_grupo:group,archivo_id:track.id}).then(r=>{const bin=atob(r.audio.base64),bytes=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)bytes[i]=bin.charCodeAt(i);url=URL.createObjectURL(new Blob([bytes],{type:r.audio.mime||'audio/mpeg'}));if(live)setState({loading:false,error:'',src:url});}).catch(e=>live&&setState({loading:false,error:contentAccessSafeUserError(e?.message||String(e),'No pudimos cargar esta pista. Intentá nuevamente.','get_audio_pista'),src:''}));return()=>{live=false;if(url)URL.revokeObjectURL(url);};},[track.id,level,codigo,group]);if(state.loading)return <small>Cargando pista…</small>;if(state.error)return <small className="error">{state.error}</small>;return <audio controls src={state.src}/>;}
  function ResourcesView({access,level,setLevel}){const d=useCatalog(level);if(d.loading)return <State>Cargando recursos…</State>;if(d.error)return <State error onRetry={d.reload}>{d.error}</State>;return <section className="ca125-page"><Header title="Recursos adicionales" desc="Material complementario oficial del nivel seleccionado." {...{access,level,setLevel}}/><div className="ca125-card"><ResourceList items={d.catalog?.recursos||[]}/>{!(d.catalog?.recursos||[]).length&&<div className="ca125-empty">No hay recursos publicados para este nivel.</div>}</div></section>;}
  function ResourceList({items,depth=0}){return <div className="ca125-resources">{(items||[]).map((x,i)=><div key={x.id||x.nombre||i} style={{marginLeft:Math.min(depth,2)*12}}><a href={x.preview_url||x.url||x.stream_url} target="_blank" rel="noreferrer"><span>{x.tipo==='folder'?'▣':'▤'}</span><strong>{x.nombre||x.titulo||'Recurso'}</strong><small>Abrir</small></a>{x.children?.length>0&&<ResourceList items={x.children} depth={depth+1}/>}</div>)}</div>;}

  function patchEnglishLab(){const access=ACCESS_CACHE.value;if(!access?.niveles_autorizados)return;const can=n=>access.niveles_autorizados.includes(n);document.querySelectorAll('.ap-bank-level-tabs button').forEach(b=>{const t=clean(b.textContent).toUpperCase(),m=t.match(/\b(B1|B2|I1|I2)\b/);if(m)b.hidden=!can(m[1]);});const minByTitle={'GRAMMAR BUILDER':'B2','LISTENING BOOST':'B2','READING FLASH':'I1'};document.querySelectorAll('.ap-card-grid-catalog > *,.ap-card-grid > *').forEach(card=>{const t=clean(card.textContent).toUpperCase();for(const title in minByTitle)if(t.includes(title)&&!can(minByTitle[title])){card.hidden=true;card.setAttribute('aria-hidden','true');}});}
  function queueLab(){loadAccess(false).then(()=>requestAnimationFrame(patchEnglishLab));}
  new MutationObserver(queueLab).observe(document.documentElement,{childList:true,subtree:true});
  document.addEventListener('click',e=>{const item=e.target.closest?.('.student-sb [data-nav-id]');if(!item)return;const route=item.dataset.navId;if(ROUTES.has(route)){e.preventDefault();e.stopImmediatePropagation();open(route,true);return;}if(currentRoute)close(true);if(route==='academia_play')queueLab();},true);
  window.addEventListener('popstate',()=>{const route=location.hash.replace(/^#/,'');if(ROUTES.has(route))open(route,false);else if(currentRoute)close(true);});
  window.addEventListener('an:session-changed',()=>{ACCESS_CACHE.value=null;ACCESS_CACHE.promise=null;close(true);});
  ensureCss();loadAccess(false).then(patchEnglishLab);
  window.StudentContentAccessCS21A125={version:VERSION,load:loadAccess,open,close,canLevel:n=>!!ACCESS_CACHE.value?.niveles_autorizados?.includes(n)};
})();
