// F98.4-Z6-CS21A73 · Planeamiento y acceso contextual al libro desde Detalle de clase
(function(){
'use strict';
const V='F98.4-Z6-CS21A73',K='an_teacher_book_open_request',T='an_teacher_materiales_tab';
const N={B1:'Básico I',B2:'Básico II',I1:'Intermedio I',I2:'Intermedio II'};
const txt=n=>String(n?.textContent||'').replace(/\s+/g,' ').trim();
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toUpperCase().replace(/\s+/g,' ').trim();
function ses(){try{return(typeof getSesion==='function'?getSesion():JSON.parse(sessionStorage.getItem('an_usuario')||'null'))||{};}catch(_){return{};}}
function code(v){return typeof v==='string'?v.trim():String(v?.code||v?.cod_grupo||v?.codigo_grupo||v?.grupo||v?.codigo||'').trim();}
function lev(v){const m=norm(v).match(/(?:^|[^A-Z0-9])(B1|B2|I1|I2)(?:[^A-Z0-9]|$)/);return m?m[1]:'';}
function level(drawer){let x=lev(txt(drawer));if(x)return x;try{x=lev(code(typeof getGrupoActivoDocente==='function'?getGrupoActivoDocente():null));if(x)return x;}catch(_){}const u=ses(),a=[u.grupoActivo,u.grupo,...(Array.isArray(u.grupos)?u.grupos:[])];for(const g of a){x=lev(code(g));if(x)return x;}return'';}
function ctx(drawer){const m=txt(drawer).match(/Lecci[oó]n\s*(\d{1,2})/i),l=Number(m?.[1]||0);return{level:level(drawer),lesson:l,unit:l?Math.min(16,Math.max(1,Math.ceil(l/2))):0,book_type:'SB',ican:/(Club\s+I\s*CAN|\bI\s*CAN\b)/i.test(txt(drawer))};}
function request(c){try{sessionStorage.setItem(T,'libros');sessionStorage.setItem(K,JSON.stringify({...c,at:Date.now()}));}catch(_){}try{dispatchEvent(new CustomEvent('an:teacher-material-tab',{detail:{tab:'libros'}}));}catch(_){}const b=[...document.querySelectorAll('aside button')].find(x=>{const s=norm(txt(x.querySelector('.sb-label')||x));return s==='LIBROS Y AUDIOS'||s==='LIBROS DE TEXTO';});if(b)b.click();}
function attach(drawer){const labels=['VER MATERIAL PDF','VER PLANEAMIENTO DE LECCION','VERIFICANDO MATERIAL...','VERIFICANDO PLANEAMIENTO...','MATERIAL NO DISPONIBLE','PLANEAMIENTO NO DISPONIBLE'];const p=[...drawer.querySelectorAll('button')].find(b=>labels.includes(norm(txt(b))));if(!p)return;const s=norm(txt(p));if(s==='VER MATERIAL PDF')p.textContent='Ver Planeamiento de Lección';else if(s==='VERIFICANDO MATERIAL...')p.textContent='Verificando planeamiento…';else if(s==='MATERIAL NO DISPONIBLE')p.textContent='Planeamiento no disponible';p.style.minWidth='190px';let b=p.parentElement?.querySelector(':scope > [data-book-cs21a73]');if(!b){b=document.createElement('button');b.type='button';b.className='btn btn-ghost';b.dataset.bookCs21a73='1';b.textContent='Ver en Libro';b.style.minWidth='150px';b.onclick=()=>{const c=ctx(b.closest('aside')||drawer);if(c.level&&c.lesson&&!c.ican)request(c);};p.insertAdjacentElement('afterend',b);}const c=ctx(drawer),off=c.ican||!c.level||!c.lesson;b.disabled=off;b.style.opacity=off?'.55':'1';b.title=c.ican?'Club I CAN no tiene unidad equivalente en el libro.':off?'No se pudo identificar nivel o lección.':`Abrir ${c.level} · SB · U${String(c.unit).padStart(2,'0')}`;}
function pending(){let r;try{r=JSON.parse(sessionStorage.getItem(K)||'null');}catch(_){return;}if(!r||!N[r.level]||Date.now()-Number(r.at||0)>300000){try{sessionStorage.removeItem(K);}catch(_){}return;}const v=document.querySelector('section[data-screen-label*="CS21A60"][data-screen-label*="Libros"]');if(!v)return;const bs=[...v.querySelectorAll('button')],lb=bs.find(b=>norm(txt(b)).startsWith(r.level+' ·'));if(lb&&!lb.classList.contains('btn-primary')){lb.click();return;}if(!norm(txt(v)).includes(norm(N[r.level])))return;const sb=bs.find(b=>norm(txt(b))==='SB');if(sb&&sb.getAttribute('aria-pressed')!=='true'){sb.click();return;}const ub=bs.find(b=>norm(txt(b))===`U${String(r.unit).padStart(2,'0')}`);if(!ub||ub.disabled)return;ub.click();try{sessionStorage.removeItem(K);ub.scrollIntoView({behavior:'smooth',block:'center',inline:'center'});}catch(_){}}
let q=false;function scan(){if(q)return;q=true;requestAnimationFrame(()=>{q=false;[...document.querySelectorAll('aside')].filter(a=>norm(txt(a)).includes('DETALLE DE CLASE')).forEach(attach);pending();});}
new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true,characterData:true});['an:teacher-material-tab','an:lazy-module-loaded','an:session-changed'].forEach(e=>addEventListener(e,scan));scan();window.__AN_TEACHER_LESSON_BOOK_LINK_VERSION__=V;
})();
